;; ============================== prooftrans ============================
;; FOF-Prover9 (32) version 2009-11A, November 2009.
;; Process 23645 was started by mccune on cleo,
;; Tue Nov  3 16:59:10 2009
;; The command was "/home/mccune/LADR/bin/fof-prover9 -f ALG033+1.in".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(13 (input) (not (= (e4) (e3))) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(66 (input) (= (op (e2) (e1)) (op (e1) (e2))) NIL)
(67A (paramod 29 (1) 66 (1)) (= (e4) (op (e1) (e2))) NIL)
(67 (paramod 24 (1) 67A (2)) (= (e4) (e3)) NIL)
(68 (resolve 67 () 13 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(59 (input) (not (= (op (op (e0) (e0)) (e0)) (op (e0) (op (e0) (e0))))) NIL)
(60A (paramod 16 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (op (e0) (op (e0) (e0))))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (op (e0) (op (e0) (e0))))) NIL)
(60C (paramod 16 (1) 60B (1 2 2)) (not (= (e0) (op (e0) (e0)))) NIL)
(60D (paramod 16 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(59 (input) (not (= (op (op (e0) (e0)) (e1)) (op (e0) (op (e0) (e1))))) NIL)
(60A (paramod 16 (1) 59 (1 1 1)) (not (= (op (e0) (e1)) (op (e0) (op (e0) (e1))))) NIL)
(60B (paramod 17 (1) 60A (1 1)) (not (= (e1) (op (e0) (op (e0) (e1))))) NIL)
(60C (paramod 17 (1) 60B (1 2 2)) (not (= (e1) (op (e0) (e1)))) NIL)
(60D (paramod 17 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(59 (input) (not (= (op (op (e0) (e0)) (e2)) (op (e0) (op (e0) (e2))))) NIL)
(60A (paramod 16 (1) 59 (1 1 1)) (not (= (op (e0) (e2)) (op (e0) (op (e0) (e2))))) NIL)
(60B (paramod 18 (1) 60A (1 1)) (not (= (e2) (op (e0) (op (e0) (e2))))) NIL)
(60C (paramod 18 (1) 60B (1 2 2)) (not (= (e2) (op (e0) (e2)))) NIL)
(60D (paramod 18 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(59 (input) (not (= (op (op (e0) (e0)) (e3)) (op (e0) (op (e0) (e3))))) NIL)
(60A (paramod 16 (1) 59 (1 1 1)) (not (= (op (e0) (e3)) (op (e0) (op (e0) (e3))))) NIL)
(60B (paramod 19 (1) 60A (1 1)) (not (= (e3) (op (e0) (op (e0) (e3))))) NIL)
(60C (paramod 19 (1) 60B (1 2 2)) (not (= (e3) (op (e0) (e3)))) NIL)
(60D (paramod 19 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(59 (input) (not (= (op (op (e0) (e0)) (e4)) (op (e0) (op (e0) (e4))))) NIL)
(60A (paramod 16 (1) 59 (1 1 1)) (not (= (op (e0) (e4)) (op (e0) (op (e0) (e4))))) NIL)
(60B (paramod 20 (1) 60A (1 1)) (not (= (e4) (op (e0) (op (e0) (e4))))) NIL)
(60C (paramod 20 (1) 60B (1 2 2)) (not (= (e4) (op (e0) (e4)))) NIL)
(60D (paramod 20 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(59 (input) (not (= (op (op (e0) (e0)) (e5)) (op (e0) (op (e0) (e5))))) NIL)
(60A (paramod 16 (1) 59 (1 1 1)) (not (= (op (e0) (e5)) (op (e0) (op (e0) (e5))))) NIL)
(60B (paramod 21 (1) 60A (1 1)) (not (= (e5) (op (e0) (op (e0) (e5))))) NIL)
(60C (paramod 21 (1) 60B (1 2 2)) (not (= (e5) (op (e0) (e5)))) NIL)
(60D (paramod 21 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(59 (input) (not (= (op (op (e0) (e1)) (e0)) (op (e0) (op (e1) (e0))))) NIL)
(60A (paramod 17 (1) 59 (1 1 1)) (not (= (op (e1) (e0)) (op (e0) (op (e1) (e0))))) NIL)
(60B (paramod 22 (1) 60A (1 1)) (not (= (e1) (op (e0) (op (e1) (e0))))) NIL)
(60C (paramod 22 (1) 60B (1 2 2)) (not (= (e1) (op (e0) (e1)))) NIL)
(60D (paramod 17 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(59 (input) (not (= (op (op (e0) (e1)) (e1)) (op (e0) (op (e1) (e1))))) NIL)
(60A (paramod 17 (1) 59 (1 1 1)) (not (= (op (e1) (e1)) (op (e0) (op (e1) (e1))))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (op (e0) (op (e1) (e1))))) NIL)
(60C (paramod 23 (1) 60B (1 2 2)) (not (= (e0) (op (e0) (e0)))) NIL)
(60D (paramod 16 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(59 (input) (not (= (op (op (e0) (e1)) (e2)) (op (e0) (op (e1) (e2))))) NIL)
(60A (paramod 17 (1) 59 (1 1 1)) (not (= (op (e1) (e2)) (op (e0) (op (e1) (e2))))) NIL)
(60B (paramod 24 (1) 60A (1 1)) (not (= (e3) (op (e0) (op (e1) (e2))))) NIL)
(60C (paramod 24 (1) 60B (1 2 2)) (not (= (e3) (op (e0) (e3)))) NIL)
(60D (paramod 19 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(59 (input) (not (= (op (op (e0) (e1)) (e3)) (op (e0) (op (e1) (e3))))) NIL)
(60A (paramod 17 (1) 59 (1 1 1)) (not (= (op (e1) (e3)) (op (e0) (op (e1) (e3))))) NIL)
(60B (paramod 25 (1) 60A (1 1)) (not (= (e2) (op (e0) (op (e1) (e3))))) NIL)
(60C (paramod 25 (1) 60B (1 2 2)) (not (= (e2) (op (e0) (e2)))) NIL)
(60D (paramod 18 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(59 (input) (not (= (op (op (e0) (e1)) (e4)) (op (e0) (op (e1) (e4))))) NIL)
(60A (paramod 17 (1) 59 (1 1 1)) (not (= (op (e1) (e4)) (op (e0) (op (e1) (e4))))) NIL)
(60B (paramod 26 (1) 60A (1 1)) (not (= (e5) (op (e0) (op (e1) (e4))))) NIL)
(60C (paramod 26 (1) 60B (1 2 2)) (not (= (e5) (op (e0) (e5)))) NIL)
(60D (paramod 21 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(59 (input) (not (= (op (op (e0) (e1)) (e5)) (op (e0) (op (e1) (e5))))) NIL)
(60A (paramod 17 (1) 59 (1 1 1)) (not (= (op (e1) (e5)) (op (e0) (op (e1) (e5))))) NIL)
(60B (paramod 27 (1) 60A (1 1)) (not (= (e4) (op (e0) (op (e1) (e5))))) NIL)
(60C (paramod 27 (1) 60B (1 2 2)) (not (= (e4) (op (e0) (e4)))) NIL)
(60D (paramod 20 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(59 (input) (not (= (op (op (e0) (e2)) (e0)) (op (e0) (op (e2) (e0))))) NIL)
(60A (paramod 18 (1) 59 (1 1 1)) (not (= (op (e2) (e0)) (op (e0) (op (e2) (e0))))) NIL)
(60B (paramod 28 (1) 60A (1 1)) (not (= (e2) (op (e0) (op (e2) (e0))))) NIL)
(60C (paramod 28 (1) 60B (1 2 2)) (not (= (e2) (op (e0) (e2)))) NIL)
(60D (paramod 18 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(59 (input) (not (= (op (op (e0) (e2)) (e1)) (op (e0) (op (e2) (e1))))) NIL)
(60A (paramod 18 (1) 59 (1 1 1)) (not (= (op (e2) (e1)) (op (e0) (op (e2) (e1))))) NIL)
(60B (paramod 29 (1) 60A (1 1)) (not (= (e4) (op (e0) (op (e2) (e1))))) NIL)
(60C (paramod 29 (1) 60B (1 2 2)) (not (= (e4) (op (e0) (e4)))) NIL)
(60D (paramod 20 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(59 (input) (not (= (op (op (e0) (e2)) (e2)) (op (e0) (op (e2) (e2))))) NIL)
(60A (paramod 18 (1) 59 (1 1 1)) (not (= (op (e2) (e2)) (op (e0) (op (e2) (e2))))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (op (e0) (op (e2) (e2))))) NIL)
(60C (paramod 30 (1) 60B (1 2 2)) (not (= (e0) (op (e0) (e0)))) NIL)
(60D (paramod 16 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(59 (input) (not (= (op (op (e0) (e2)) (e3)) (op (e0) (op (e2) (e3))))) NIL)
(60A (paramod 18 (1) 59 (1 1 1)) (not (= (op (e2) (e3)) (op (e0) (op (e2) (e3))))) NIL)
(60B (paramod 31 (1) 60A (1 1)) (not (= (e5) (op (e0) (op (e2) (e3))))) NIL)
(60C (paramod 31 (1) 60B (1 2 2)) (not (= (e5) (op (e0) (e5)))) NIL)
(60D (paramod 21 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(59 (input) (not (= (op (op (e0) (e2)) (e4)) (op (e0) (op (e2) (e4))))) NIL)
(60A (paramod 18 (1) 59 (1 1 1)) (not (= (op (e2) (e4)) (op (e0) (op (e2) (e4))))) NIL)
(60B (paramod 32 (1) 60A (1 1)) (not (= (e1) (op (e0) (op (e2) (e4))))) NIL)
(60C (paramod 32 (1) 60B (1 2 2)) (not (= (e1) (op (e0) (e1)))) NIL)
(60D (paramod 17 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(59 (input) (not (= (op (op (e0) (e2)) (e5)) (op (e0) (op (e2) (e5))))) NIL)
(60A (paramod 18 (1) 59 (1 1 1)) (not (= (op (e2) (e5)) (op (e0) (op (e2) (e5))))) NIL)
(60B (paramod 33 (1) 60A (1 1)) (not (= (e3) (op (e0) (op (e2) (e5))))) NIL)
(60C (paramod 33 (1) 60B (1 2 2)) (not (= (e3) (op (e0) (e3)))) NIL)
(60D (paramod 19 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(59 (input) (not (= (op (op (e0) (e3)) (e0)) (op (e0) (op (e3) (e0))))) NIL)
(60A (paramod 19 (1) 59 (1 1 1)) (not (= (op (e3) (e0)) (op (e0) (op (e3) (e0))))) NIL)
(60B (paramod 34 (1) 60A (1 1)) (not (= (e3) (op (e0) (op (e3) (e0))))) NIL)
(60C (paramod 34 (1) 60B (1 2 2)) (not (= (e3) (op (e0) (e3)))) NIL)
(60D (paramod 19 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(59 (input) (not (= (op (op (e0) (e3)) (e1)) (op (e0) (op (e3) (e1))))) NIL)
(60A (paramod 19 (1) 59 (1 1 1)) (not (= (op (e3) (e1)) (op (e0) (op (e3) (e1))))) NIL)
(60B (paramod 35 (1) 60A (1 1)) (not (= (e5) (op (e0) (op (e3) (e1))))) NIL)
(60C (paramod 35 (1) 60B (1 2 2)) (not (= (e5) (op (e0) (e5)))) NIL)
(60D (paramod 21 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(59 (input) (not (= (op (op (e0) (e3)) (e2)) (op (e0) (op (e3) (e2))))) NIL)
(60A (paramod 19 (1) 59 (1 1 1)) (not (= (op (e3) (e2)) (op (e0) (op (e3) (e2))))) NIL)
(60B (paramod 36 (1) 60A (1 1)) (not (= (e1) (op (e0) (op (e3) (e2))))) NIL)
(60C (paramod 36 (1) 60B (1 2 2)) (not (= (e1) (op (e0) (e1)))) NIL)
(60D (paramod 17 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(59 (input) (not (= (op (op (e0) (e3)) (e3)) (op (e0) (op (e3) (e3))))) NIL)
(60A (paramod 19 (1) 59 (1 1 1)) (not (= (op (e3) (e3)) (op (e0) (op (e3) (e3))))) NIL)
(60B (paramod 37 (1) 60A (1 1)) (not (= (e4) (op (e0) (op (e3) (e3))))) NIL)
(60C (paramod 37 (1) 60B (1 2 2)) (not (= (e4) (op (e0) (e4)))) NIL)
(60D (paramod 20 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(59 (input) (not (= (op (op (e0) (e3)) (e4)) (op (e0) (op (e3) (e4))))) NIL)
(60A (paramod 19 (1) 59 (1 1 1)) (not (= (op (e3) (e4)) (op (e0) (op (e3) (e4))))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (op (e0) (op (e3) (e4))))) NIL)
(60C (paramod 38 (1) 60B (1 2 2)) (not (= (e0) (op (e0) (e0)))) NIL)
(60D (paramod 16 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(59 (input) (not (= (op (op (e0) (e3)) (e5)) (op (e0) (op (e3) (e5))))) NIL)
(60A (paramod 19 (1) 59 (1 1 1)) (not (= (op (e3) (e5)) (op (e0) (op (e3) (e5))))) NIL)
(60B (paramod 39 (1) 60A (1 1)) (not (= (e2) (op (e0) (op (e3) (e5))))) NIL)
(60C (paramod 39 (1) 60B (1 2 2)) (not (= (e2) (op (e0) (e2)))) NIL)
(60D (paramod 18 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(59 (input) (not (= (op (op (e0) (e4)) (e0)) (op (e0) (op (e4) (e0))))) NIL)
(60A (paramod 20 (1) 59 (1 1 1)) (not (= (op (e4) (e0)) (op (e0) (op (e4) (e0))))) NIL)
(60B (paramod 40 (1) 60A (1 1)) (not (= (e4) (op (e0) (op (e4) (e0))))) NIL)
(60C (paramod 40 (1) 60B (1 2 2)) (not (= (e4) (op (e0) (e4)))) NIL)
(60D (paramod 20 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e0) (e4)) (e1)) (op (e0) (op (e4) (e1))))) NIL)
(60A (paramod 20 (1) 59 (1 1 1)) (not (= (op (e4) (e1)) (op (e0) (op (e4) (e1))))) NIL)
(60B (paramod 41 (1) 60A (1 1)) (not (= (e2) (op (e0) (op (e4) (e1))))) NIL)
(60C (paramod 41 (1) 60B (1 2 2)) (not (= (e2) (op (e0) (e2)))) NIL)
(60D (paramod 18 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(59 (input) (not (= (op (op (e0) (e4)) (e2)) (op (e0) (op (e4) (e2))))) NIL)
(60A (paramod 20 (1) 59 (1 1 1)) (not (= (op (e4) (e2)) (op (e0) (op (e4) (e2))))) NIL)
(60B (paramod 42 (1) 60A (1 1)) (not (= (e5) (op (e0) (op (e4) (e2))))) NIL)
(60C (paramod 42 (1) 60B (1 2 2)) (not (= (e5) (op (e0) (e5)))) NIL)
(60D (paramod 21 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e0) (e4)) (e3)) (op (e0) (op (e4) (e3))))) NIL)
(60A (paramod 20 (1) 59 (1 1 1)) (not (= (op (e4) (e3)) (op (e0) (op (e4) (e3))))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (op (e0) (op (e4) (e3))))) NIL)
(60C (paramod 43 (1) 60B (1 2 2)) (not (= (e0) (op (e0) (e0)))) NIL)
(60D (paramod 16 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e0) (e4)) (e4)) (op (e0) (op (e4) (e4))))) NIL)
(60A (paramod 20 (1) 59 (1 1 1)) (not (= (op (e4) (e4)) (op (e0) (op (e4) (e4))))) NIL)
(60B (paramod 44 (1) 60A (1 1)) (not (= (e3) (op (e0) (op (e4) (e4))))) NIL)
(60C (paramod 44 (1) 60B (1 2 2)) (not (= (e3) (op (e0) (e3)))) NIL)
(60D (paramod 19 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e0) (e4)) (e5)) (op (e0) (op (e4) (e5))))) NIL)
(60A (paramod 20 (1) 59 (1 1 1)) (not (= (op (e4) (e5)) (op (e0) (op (e4) (e5))))) NIL)
(60B (paramod 45 (1) 60A (1 1)) (not (= (e1) (op (e0) (op (e4) (e5))))) NIL)
(60C (paramod 45 (1) 60B (1 2 2)) (not (= (e1) (op (e0) (e1)))) NIL)
(60D (paramod 17 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e0) (e5)) (e0)) (op (e0) (op (e5) (e0))))) NIL)
(60A (paramod 21 (1) 59 (1 1 1)) (not (= (op (e5) (e0)) (op (e0) (op (e5) (e0))))) NIL)
(60B (paramod 46 (1) 60A (1 1)) (not (= (e5) (op (e0) (op (e5) (e0))))) NIL)
(60C (paramod 46 (1) 60B (1 2 2)) (not (= (e5) (op (e0) (e5)))) NIL)
(60D (paramod 21 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e0) (e5)) (e1)) (op (e0) (op (e5) (e1))))) NIL)
(60A (paramod 21 (1) 59 (1 1 1)) (not (= (op (e5) (e1)) (op (e0) (op (e5) (e1))))) NIL)
(60B (paramod 47 (1) 60A (1 1)) (not (= (e3) (op (e0) (op (e5) (e1))))) NIL)
(60C (paramod 47 (1) 60B (1 2 2)) (not (= (e3) (op (e0) (e3)))) NIL)
(60D (paramod 19 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e0) (e5)) (e2)) (op (e0) (op (e5) (e2))))) NIL)
(60A (paramod 21 (1) 59 (1 1 1)) (not (= (op (e5) (e2)) (op (e0) (op (e5) (e2))))) NIL)
(60B (paramod 48 (1) 60A (1 1)) (not (= (e4) (op (e0) (op (e5) (e2))))) NIL)
(60C (paramod 48 (1) 60B (1 2 2)) (not (= (e4) (op (e0) (e4)))) NIL)
(60D (paramod 20 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e0) (e5)) (e3)) (op (e0) (op (e5) (e3))))) NIL)
(60A (paramod 21 (1) 59 (1 1 1)) (not (= (op (e5) (e3)) (op (e0) (op (e5) (e3))))) NIL)
(60B (paramod 49 (1) 60A (1 1)) (not (= (e1) (op (e0) (op (e5) (e3))))) NIL)
(60C (paramod 49 (1) 60B (1 2 2)) (not (= (e1) (op (e0) (e1)))) NIL)
(60D (paramod 17 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e0) (e5)) (e4)) (op (e0) (op (e5) (e4))))) NIL)
(60A (paramod 21 (1) 59 (1 1 1)) (not (= (op (e5) (e4)) (op (e0) (op (e5) (e4))))) NIL)
(60B (paramod 50 (1) 60A (1 1)) (not (= (e2) (op (e0) (op (e5) (e4))))) NIL)
(60C (paramod 50 (1) 60B (1 2 2)) (not (= (e2) (op (e0) (e2)))) NIL)
(60D (paramod 18 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e0) (e5)) (e5)) (op (e0) (op (e5) (e5))))) NIL)
(60A (paramod 21 (1) 59 (1 1 1)) (not (= (op (e5) (e5)) (op (e0) (op (e5) (e5))))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (op (e0) (op (e5) (e5))))) NIL)
(60C (paramod 51 (1) 60B (1 2 2)) (not (= (e0) (op (e0) (e0)))) NIL)
(60D (paramod 16 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(59 (input) (not (= (op (op (e1) (e0)) (e0)) (op (e1) (op (e0) (e0))))) NIL)
(60A (paramod 22 (1) 59 (1 1 1)) (not (= (op (e1) (e0)) (op (e1) (op (e0) (e0))))) NIL)
(60B (paramod 22 (1) 60A (1 1)) (not (= (e1) (op (e1) (op (e0) (e0))))) NIL)
(60C (paramod 16 (1) 60B (1 2 2)) (not (= (e1) (op (e1) (e0)))) NIL)
(60D (paramod 22 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(59 (input) (not (= (op (op (e1) (e0)) (e1)) (op (e1) (op (e0) (e1))))) NIL)
(60A (paramod 22 (1) 59 (1 1 1)) (not (= (op (e1) (e1)) (op (e1) (op (e0) (e1))))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (op (e1) (op (e0) (e1))))) NIL)
(60C (paramod 17 (1) 60B (1 2 2)) (not (= (e0) (op (e1) (e1)))) NIL)
(60D (paramod 23 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(59 (input) (not (= (op (op (e1) (e0)) (e2)) (op (e1) (op (e0) (e2))))) NIL)
(60A (paramod 22 (1) 59 (1 1 1)) (not (= (op (e1) (e2)) (op (e1) (op (e0) (e2))))) NIL)
(60B (paramod 24 (1) 60A (1 1)) (not (= (e3) (op (e1) (op (e0) (e2))))) NIL)
(60C (paramod 18 (1) 60B (1 2 2)) (not (= (e3) (op (e1) (e2)))) NIL)
(60D (paramod 24 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(59 (input) (not (= (op (op (e1) (e0)) (e3)) (op (e1) (op (e0) (e3))))) NIL)
(60A (paramod 22 (1) 59 (1 1 1)) (not (= (op (e1) (e3)) (op (e1) (op (e0) (e3))))) NIL)
(60B (paramod 25 (1) 60A (1 1)) (not (= (e2) (op (e1) (op (e0) (e3))))) NIL)
(60C (paramod 19 (1) 60B (1 2 2)) (not (= (e2) (op (e1) (e3)))) NIL)
(60D (paramod 25 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(59 (input) (not (= (op (op (e1) (e0)) (e4)) (op (e1) (op (e0) (e4))))) NIL)
(60A (paramod 22 (1) 59 (1 1 1)) (not (= (op (e1) (e4)) (op (e1) (op (e0) (e4))))) NIL)
(60B (paramod 26 (1) 60A (1 1)) (not (= (e5) (op (e1) (op (e0) (e4))))) NIL)
(60C (paramod 20 (1) 60B (1 2 2)) (not (= (e5) (op (e1) (e4)))) NIL)
(60D (paramod 26 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(59 (input) (not (= (op (op (e1) (e0)) (e5)) (op (e1) (op (e0) (e5))))) NIL)
(60A (paramod 22 (1) 59 (1 1 1)) (not (= (op (e1) (e5)) (op (e1) (op (e0) (e5))))) NIL)
(60B (paramod 27 (1) 60A (1 1)) (not (= (e4) (op (e1) (op (e0) (e5))))) NIL)
(60C (paramod 21 (1) 60B (1 2 2)) (not (= (e4) (op (e1) (e5)))) NIL)
(60D (paramod 27 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(59 (input) (not (= (op (op (e1) (e1)) (e0)) (op (e1) (op (e1) (e0))))) NIL)
(60A (paramod 23 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (op (e1) (op (e1) (e0))))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (op (e1) (op (e1) (e0))))) NIL)
(60C (paramod 22 (1) 60B (1 2 2)) (not (= (e0) (op (e1) (e1)))) NIL)
(60D (paramod 23 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(59 (input) (not (= (op (op (e1) (e1)) (e1)) (op (e1) (op (e1) (e1))))) NIL)
(60A (paramod 23 (1) 59 (1 1 1)) (not (= (op (e0) (e1)) (op (e1) (op (e1) (e1))))) NIL)
(60B (paramod 17 (1) 60A (1 1)) (not (= (e1) (op (e1) (op (e1) (e1))))) NIL)
(60C (paramod 23 (1) 60B (1 2 2)) (not (= (e1) (op (e1) (e0)))) NIL)
(60D (paramod 22 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(59 (input) (not (= (op (op (e1) (e1)) (e2)) (op (e1) (op (e1) (e2))))) NIL)
(60A (paramod 23 (1) 59 (1 1 1)) (not (= (op (e0) (e2)) (op (e1) (op (e1) (e2))))) NIL)
(60B (paramod 18 (1) 60A (1 1)) (not (= (e2) (op (e1) (op (e1) (e2))))) NIL)
(60C (paramod 24 (1) 60B (1 2 2)) (not (= (e2) (op (e1) (e3)))) NIL)
(60D (paramod 25 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(59 (input) (not (= (op (op (e1) (e1)) (e3)) (op (e1) (op (e1) (e3))))) NIL)
(60A (paramod 23 (1) 59 (1 1 1)) (not (= (op (e0) (e3)) (op (e1) (op (e1) (e3))))) NIL)
(60B (paramod 19 (1) 60A (1 1)) (not (= (e3) (op (e1) (op (e1) (e3))))) NIL)
(60C (paramod 25 (1) 60B (1 2 2)) (not (= (e3) (op (e1) (e2)))) NIL)
(60D (paramod 24 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(59 (input) (not (= (op (op (e1) (e1)) (e4)) (op (e1) (op (e1) (e4))))) NIL)
(60A (paramod 23 (1) 59 (1 1 1)) (not (= (op (e0) (e4)) (op (e1) (op (e1) (e4))))) NIL)
(60B (paramod 20 (1) 60A (1 1)) (not (= (e4) (op (e1) (op (e1) (e4))))) NIL)
(60C (paramod 26 (1) 60B (1 2 2)) (not (= (e4) (op (e1) (e5)))) NIL)
(60D (paramod 27 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(59 (input) (not (= (op (op (e1) (e1)) (e5)) (op (e1) (op (e1) (e5))))) NIL)
(60A (paramod 23 (1) 59 (1 1 1)) (not (= (op (e0) (e5)) (op (e1) (op (e1) (e5))))) NIL)
(60B (paramod 21 (1) 60A (1 1)) (not (= (e5) (op (e1) (op (e1) (e5))))) NIL)
(60C (paramod 27 (1) 60B (1 2 2)) (not (= (e5) (op (e1) (e4)))) NIL)
(60D (paramod 26 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(59 (input) (not (= (op (op (e1) (e2)) (e0)) (op (e1) (op (e2) (e0))))) NIL)
(60A (paramod 24 (1) 59 (1 1 1)) (not (= (op (e3) (e0)) (op (e1) (op (e2) (e0))))) NIL)
(60B (paramod 34 (1) 60A (1 1)) (not (= (e3) (op (e1) (op (e2) (e0))))) NIL)
(60C (paramod 28 (1) 60B (1 2 2)) (not (= (e3) (op (e1) (e2)))) NIL)
(60D (paramod 24 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(59 (input) (not (= (op (op (e1) (e2)) (e1)) (op (e1) (op (e2) (e1))))) NIL)
(60A (paramod 24 (1) 59 (1 1 1)) (not (= (op (e3) (e1)) (op (e1) (op (e2) (e1))))) NIL)
(60B (paramod 35 (1) 60A (1 1)) (not (= (e5) (op (e1) (op (e2) (e1))))) NIL)
(60C (paramod 29 (1) 60B (1 2 2)) (not (= (e5) (op (e1) (e4)))) NIL)
(60D (paramod 26 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(59 (input) (not (= (op (op (e1) (e2)) (e2)) (op (e1) (op (e2) (e2))))) NIL)
(60A (paramod 24 (1) 59 (1 1 1)) (not (= (op (e3) (e2)) (op (e1) (op (e2) (e2))))) NIL)
(60B (paramod 36 (1) 60A (1 1)) (not (= (e1) (op (e1) (op (e2) (e2))))) NIL)
(60C (paramod 30 (1) 60B (1 2 2)) (not (= (e1) (op (e1) (e0)))) NIL)
(60D (paramod 22 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(59 (input) (not (= (op (op (e1) (e2)) (e3)) (op (e1) (op (e2) (e3))))) NIL)
(60A (paramod 24 (1) 59 (1 1 1)) (not (= (op (e3) (e3)) (op (e1) (op (e2) (e3))))) NIL)
(60B (paramod 37 (1) 60A (1 1)) (not (= (e4) (op (e1) (op (e2) (e3))))) NIL)
(60C (paramod 31 (1) 60B (1 2 2)) (not (= (e4) (op (e1) (e5)))) NIL)
(60D (paramod 27 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(59 (input) (not (= (op (op (e1) (e2)) (e4)) (op (e1) (op (e2) (e4))))) NIL)
(60A (paramod 24 (1) 59 (1 1 1)) (not (= (op (e3) (e4)) (op (e1) (op (e2) (e4))))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (op (e1) (op (e2) (e4))))) NIL)
(60C (paramod 32 (1) 60B (1 2 2)) (not (= (e0) (op (e1) (e1)))) NIL)
(60D (paramod 23 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(59 (input) (not (= (op (op (e1) (e2)) (e5)) (op (e1) (op (e2) (e5))))) NIL)
(60A (paramod 24 (1) 59 (1 1 1)) (not (= (op (e3) (e5)) (op (e1) (op (e2) (e5))))) NIL)
(60B (paramod 39 (1) 60A (1 1)) (not (= (e2) (op (e1) (op (e2) (e5))))) NIL)
(60C (paramod 33 (1) 60B (1 2 2)) (not (= (e2) (op (e1) (e3)))) NIL)
(60D (paramod 25 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(59 (input) (not (= (op (op (e1) (e3)) (e0)) (op (e1) (op (e3) (e0))))) NIL)
(60A (paramod 25 (1) 59 (1 1 1)) (not (= (op (e2) (e0)) (op (e1) (op (e3) (e0))))) NIL)
(60B (paramod 28 (1) 60A (1 1)) (not (= (e2) (op (e1) (op (e3) (e0))))) NIL)
(60C (paramod 34 (1) 60B (1 2 2)) (not (= (e2) (op (e1) (e3)))) NIL)
(60D (paramod 25 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(59 (input) (not (= (op (op (e1) (e3)) (e1)) (op (e1) (op (e3) (e1))))) NIL)
(60A (paramod 25 (1) 59 (1 1 1)) (not (= (op (e2) (e1)) (op (e1) (op (e3) (e1))))) NIL)
(60B (paramod 29 (1) 60A (1 1)) (not (= (e4) (op (e1) (op (e3) (e1))))) NIL)
(60C (paramod 35 (1) 60B (1 2 2)) (not (= (e4) (op (e1) (e5)))) NIL)
(60D (paramod 27 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(59 (input) (not (= (op (op (e1) (e3)) (e2)) (op (e1) (op (e3) (e2))))) NIL)
(60A (paramod 25 (1) 59 (1 1 1)) (not (= (op (e2) (e2)) (op (e1) (op (e3) (e2))))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (op (e1) (op (e3) (e2))))) NIL)
(60C (paramod 36 (1) 60B (1 2 2)) (not (= (e0) (op (e1) (e1)))) NIL)
(60D (paramod 23 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(59 (input) (not (= (op (op (e1) (e3)) (e3)) (op (e1) (op (e3) (e3))))) NIL)
(60A (paramod 25 (1) 59 (1 1 1)) (not (= (op (e2) (e3)) (op (e1) (op (e3) (e3))))) NIL)
(60B (paramod 31 (1) 60A (1 1)) (not (= (e5) (op (e1) (op (e3) (e3))))) NIL)
(60C (paramod 37 (1) 60B (1 2 2)) (not (= (e5) (op (e1) (e4)))) NIL)
(60D (paramod 26 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(59 (input) (not (= (op (op (e1) (e3)) (e4)) (op (e1) (op (e3) (e4))))) NIL)
(60A (paramod 25 (1) 59 (1 1 1)) (not (= (op (e2) (e4)) (op (e1) (op (e3) (e4))))) NIL)
(60B (paramod 32 (1) 60A (1 1)) (not (= (e1) (op (e1) (op (e3) (e4))))) NIL)
(60C (paramod 38 (1) 60B (1 2 2)) (not (= (e1) (op (e1) (e0)))) NIL)
(60D (paramod 22 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(59 (input) (not (= (op (op (e1) (e3)) (e5)) (op (e1) (op (e3) (e5))))) NIL)
(60A (paramod 25 (1) 59 (1 1 1)) (not (= (op (e2) (e5)) (op (e1) (op (e3) (e5))))) NIL)
(60B (paramod 33 (1) 60A (1 1)) (not (= (e3) (op (e1) (op (e3) (e5))))) NIL)
(60C (paramod 39 (1) 60B (1 2 2)) (not (= (e3) (op (e1) (e2)))) NIL)
(60D (paramod 24 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e1) (e4)) (e0)) (op (e1) (op (e4) (e0))))) NIL)
(60A (paramod 26 (1) 59 (1 1 1)) (not (= (op (e5) (e0)) (op (e1) (op (e4) (e0))))) NIL)
(60B (paramod 46 (1) 60A (1 1)) (not (= (e5) (op (e1) (op (e4) (e0))))) NIL)
(60C (paramod 40 (1) 60B (1 2 2)) (not (= (e5) (op (e1) (e4)))) NIL)
(60D (paramod 26 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e1) (e4)) (e1)) (op (e1) (op (e4) (e1))))) NIL)
(60A (paramod 26 (1) 59 (1 1 1)) (not (= (op (e5) (e1)) (op (e1) (op (e4) (e1))))) NIL)
(60B (paramod 47 (1) 60A (1 1)) (not (= (e3) (op (e1) (op (e4) (e1))))) NIL)
(60C (paramod 41 (1) 60B (1 2 2)) (not (= (e3) (op (e1) (e2)))) NIL)
(60D (paramod 24 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e1) (e4)) (e2)) (op (e1) (op (e4) (e2))))) NIL)
(60A (paramod 26 (1) 59 (1 1 1)) (not (= (op (e5) (e2)) (op (e1) (op (e4) (e2))))) NIL)
(60B (paramod 48 (1) 60A (1 1)) (not (= (e4) (op (e1) (op (e4) (e2))))) NIL)
(60C (paramod 42 (1) 60B (1 2 2)) (not (= (e4) (op (e1) (e5)))) NIL)
(60D (paramod 27 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e1) (e4)) (e3)) (op (e1) (op (e4) (e3))))) NIL)
(60A (paramod 26 (1) 59 (1 1 1)) (not (= (op (e5) (e3)) (op (e1) (op (e4) (e3))))) NIL)
(60B (paramod 49 (1) 60A (1 1)) (not (= (e1) (op (e1) (op (e4) (e3))))) NIL)
(60C (paramod 43 (1) 60B (1 2 2)) (not (= (e1) (op (e1) (e0)))) NIL)
(60D (paramod 22 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e1) (e4)) (e4)) (op (e1) (op (e4) (e4))))) NIL)
(60A (paramod 26 (1) 59 (1 1 1)) (not (= (op (e5) (e4)) (op (e1) (op (e4) (e4))))) NIL)
(60B (paramod 50 (1) 60A (1 1)) (not (= (e2) (op (e1) (op (e4) (e4))))) NIL)
(60C (paramod 44 (1) 60B (1 2 2)) (not (= (e2) (op (e1) (e3)))) NIL)
(60D (paramod 25 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e1) (e4)) (e5)) (op (e1) (op (e4) (e5))))) NIL)
(60A (paramod 26 (1) 59 (1 1 1)) (not (= (op (e5) (e5)) (op (e1) (op (e4) (e5))))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (op (e1) (op (e4) (e5))))) NIL)
(60C (paramod 45 (1) 60B (1 2 2)) (not (= (e0) (op (e1) (e1)))) NIL)
(60D (paramod 23 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e1) (e5)) (e0)) (op (e1) (op (e5) (e0))))) NIL)
(60A (paramod 27 (1) 59 (1 1 1)) (not (= (op (e4) (e0)) (op (e1) (op (e5) (e0))))) NIL)
(60B (paramod 40 (1) 60A (1 1)) (not (= (e4) (op (e1) (op (e5) (e0))))) NIL)
(60C (paramod 46 (1) 60B (1 2 2)) (not (= (e4) (op (e1) (e5)))) NIL)
(60D (paramod 27 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e1) (e5)) (e1)) (op (e1) (op (e5) (e1))))) NIL)
(60A (paramod 27 (1) 59 (1 1 1)) (not (= (op (e4) (e1)) (op (e1) (op (e5) (e1))))) NIL)
(60B (paramod 41 (1) 60A (1 1)) (not (= (e2) (op (e1) (op (e5) (e1))))) NIL)
(60C (paramod 47 (1) 60B (1 2 2)) (not (= (e2) (op (e1) (e3)))) NIL)
(60D (paramod 25 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e1) (e5)) (e2)) (op (e1) (op (e5) (e2))))) NIL)
(60A (paramod 27 (1) 59 (1 1 1)) (not (= (op (e4) (e2)) (op (e1) (op (e5) (e2))))) NIL)
(60B (paramod 42 (1) 60A (1 1)) (not (= (e5) (op (e1) (op (e5) (e2))))) NIL)
(60C (paramod 48 (1) 60B (1 2 2)) (not (= (e5) (op (e1) (e4)))) NIL)
(60D (paramod 26 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e1) (e5)) (e3)) (op (e1) (op (e5) (e3))))) NIL)
(60A (paramod 27 (1) 59 (1 1 1)) (not (= (op (e4) (e3)) (op (e1) (op (e5) (e3))))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (op (e1) (op (e5) (e3))))) NIL)
(60C (paramod 49 (1) 60B (1 2 2)) (not (= (e0) (op (e1) (e1)))) NIL)
(60D (paramod 23 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e1) (e5)) (e4)) (op (e1) (op (e5) (e4))))) NIL)
(60A (paramod 27 (1) 59 (1 1 1)) (not (= (op (e4) (e4)) (op (e1) (op (e5) (e4))))) NIL)
(60B (paramod 44 (1) 60A (1 1)) (not (= (e3) (op (e1) (op (e5) (e4))))) NIL)
(60C (paramod 50 (1) 60B (1 2 2)) (not (= (e3) (op (e1) (e2)))) NIL)
(60D (paramod 24 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e1) (e5)) (e5)) (op (e1) (op (e5) (e5))))) NIL)
(60A (paramod 27 (1) 59 (1 1 1)) (not (= (op (e4) (e5)) (op (e1) (op (e5) (e5))))) NIL)
(60B (paramod 45 (1) 60A (1 1)) (not (= (e1) (op (e1) (op (e5) (e5))))) NIL)
(60C (paramod 51 (1) 60B (1 2 2)) (not (= (e1) (op (e1) (e0)))) NIL)
(60D (paramod 22 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(59 (input) (not (= (op (op (e2) (e0)) (e0)) (op (e2) (op (e0) (e0))))) NIL)
(60A (paramod 28 (1) 59 (1 1 1)) (not (= (op (e2) (e0)) (op (e2) (op (e0) (e0))))) NIL)
(60B (paramod 28 (1) 60A (1 1)) (not (= (e2) (op (e2) (op (e0) (e0))))) NIL)
(60C (paramod 16 (1) 60B (1 2 2)) (not (= (e2) (op (e2) (e0)))) NIL)
(60D (paramod 28 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(59 (input) (not (= (op (op (e2) (e0)) (e1)) (op (e2) (op (e0) (e1))))) NIL)
(60A (paramod 28 (1) 59 (1 1 1)) (not (= (op (e2) (e1)) (op (e2) (op (e0) (e1))))) NIL)
(60B (paramod 29 (1) 60A (1 1)) (not (= (e4) (op (e2) (op (e0) (e1))))) NIL)
(60C (paramod 17 (1) 60B (1 2 2)) (not (= (e4) (op (e2) (e1)))) NIL)
(60D (paramod 29 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(59 (input) (not (= (op (op (e2) (e0)) (e2)) (op (e2) (op (e0) (e2))))) NIL)
(60A (paramod 28 (1) 59 (1 1 1)) (not (= (op (e2) (e2)) (op (e2) (op (e0) (e2))))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (op (e2) (op (e0) (e2))))) NIL)
(60C (paramod 18 (1) 60B (1 2 2)) (not (= (e0) (op (e2) (e2)))) NIL)
(60D (paramod 30 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(59 (input) (not (= (op (op (e2) (e0)) (e3)) (op (e2) (op (e0) (e3))))) NIL)
(60A (paramod 28 (1) 59 (1 1 1)) (not (= (op (e2) (e3)) (op (e2) (op (e0) (e3))))) NIL)
(60B (paramod 31 (1) 60A (1 1)) (not (= (e5) (op (e2) (op (e0) (e3))))) NIL)
(60C (paramod 19 (1) 60B (1 2 2)) (not (= (e5) (op (e2) (e3)))) NIL)
(60D (paramod 31 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(59 (input) (not (= (op (op (e2) (e0)) (e4)) (op (e2) (op (e0) (e4))))) NIL)
(60A (paramod 28 (1) 59 (1 1 1)) (not (= (op (e2) (e4)) (op (e2) (op (e0) (e4))))) NIL)
(60B (paramod 32 (1) 60A (1 1)) (not (= (e1) (op (e2) (op (e0) (e4))))) NIL)
(60C (paramod 20 (1) 60B (1 2 2)) (not (= (e1) (op (e2) (e4)))) NIL)
(60D (paramod 32 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(59 (input) (not (= (op (op (e2) (e0)) (e5)) (op (e2) (op (e0) (e5))))) NIL)
(60A (paramod 28 (1) 59 (1 1 1)) (not (= (op (e2) (e5)) (op (e2) (op (e0) (e5))))) NIL)
(60B (paramod 33 (1) 60A (1 1)) (not (= (e3) (op (e2) (op (e0) (e5))))) NIL)
(60C (paramod 21 (1) 60B (1 2 2)) (not (= (e3) (op (e2) (e5)))) NIL)
(60D (paramod 33 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(59 (input) (not (= (op (op (e2) (e1)) (e0)) (op (e2) (op (e1) (e0))))) NIL)
(60A (paramod 29 (1) 59 (1 1 1)) (not (= (op (e4) (e0)) (op (e2) (op (e1) (e0))))) NIL)
(60B (paramod 40 (1) 60A (1 1)) (not (= (e4) (op (e2) (op (e1) (e0))))) NIL)
(60C (paramod 22 (1) 60B (1 2 2)) (not (= (e4) (op (e2) (e1)))) NIL)
(60D (paramod 29 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e2) (e1)) (e1)) (op (e2) (op (e1) (e1))))) NIL)
(60A (paramod 29 (1) 59 (1 1 1)) (not (= (op (e4) (e1)) (op (e2) (op (e1) (e1))))) NIL)
(60B (paramod 41 (1) 60A (1 1)) (not (= (e2) (op (e2) (op (e1) (e1))))) NIL)
(60C (paramod 23 (1) 60B (1 2 2)) (not (= (e2) (op (e2) (e0)))) NIL)
(60D (paramod 28 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(59 (input) (not (= (op (op (e2) (e1)) (e2)) (op (e2) (op (e1) (e2))))) NIL)
(60A (paramod 29 (1) 59 (1 1 1)) (not (= (op (e4) (e2)) (op (e2) (op (e1) (e2))))) NIL)
(60B (paramod 42 (1) 60A (1 1)) (not (= (e5) (op (e2) (op (e1) (e2))))) NIL)
(60C (paramod 24 (1) 60B (1 2 2)) (not (= (e5) (op (e2) (e3)))) NIL)
(60D (paramod 31 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e2) (e1)) (e3)) (op (e2) (op (e1) (e3))))) NIL)
(60A (paramod 29 (1) 59 (1 1 1)) (not (= (op (e4) (e3)) (op (e2) (op (e1) (e3))))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (op (e2) (op (e1) (e3))))) NIL)
(60C (paramod 25 (1) 60B (1 2 2)) (not (= (e0) (op (e2) (e2)))) NIL)
(60D (paramod 30 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e2) (e1)) (e4)) (op (e2) (op (e1) (e4))))) NIL)
(60A (paramod 29 (1) 59 (1 1 1)) (not (= (op (e4) (e4)) (op (e2) (op (e1) (e4))))) NIL)
(60B (paramod 44 (1) 60A (1 1)) (not (= (e3) (op (e2) (op (e1) (e4))))) NIL)
(60C (paramod 26 (1) 60B (1 2 2)) (not (= (e3) (op (e2) (e5)))) NIL)
(60D (paramod 33 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e2) (e1)) (e5)) (op (e2) (op (e1) (e5))))) NIL)
(60A (paramod 29 (1) 59 (1 1 1)) (not (= (op (e4) (e5)) (op (e2) (op (e1) (e5))))) NIL)
(60B (paramod 45 (1) 60A (1 1)) (not (= (e1) (op (e2) (op (e1) (e5))))) NIL)
(60C (paramod 27 (1) 60B (1 2 2)) (not (= (e1) (op (e2) (e4)))) NIL)
(60D (paramod 32 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(59 (input) (not (= (op (op (e2) (e2)) (e0)) (op (e2) (op (e2) (e0))))) NIL)
(60A (paramod 30 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (op (e2) (op (e2) (e0))))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (op (e2) (op (e2) (e0))))) NIL)
(60C (paramod 28 (1) 60B (1 2 2)) (not (= (e0) (op (e2) (e2)))) NIL)
(60D (paramod 30 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(59 (input) (not (= (op (op (e2) (e2)) (e1)) (op (e2) (op (e2) (e1))))) NIL)
(60A (paramod 30 (1) 59 (1 1 1)) (not (= (op (e0) (e1)) (op (e2) (op (e2) (e1))))) NIL)
(60B (paramod 17 (1) 60A (1 1)) (not (= (e1) (op (e2) (op (e2) (e1))))) NIL)
(60C (paramod 29 (1) 60B (1 2 2)) (not (= (e1) (op (e2) (e4)))) NIL)
(60D (paramod 32 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(59 (input) (not (= (op (op (e2) (e2)) (e2)) (op (e2) (op (e2) (e2))))) NIL)
(60A (paramod 30 (1) 59 (1 1 1)) (not (= (op (e0) (e2)) (op (e2) (op (e2) (e2))))) NIL)
(60B (paramod 18 (1) 60A (1 1)) (not (= (e2) (op (e2) (op (e2) (e2))))) NIL)
(60C (paramod 30 (1) 60B (1 2 2)) (not (= (e2) (op (e2) (e0)))) NIL)
(60D (paramod 28 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(59 (input) (not (= (op (op (e2) (e2)) (e3)) (op (e2) (op (e2) (e3))))) NIL)
(60A (paramod 30 (1) 59 (1 1 1)) (not (= (op (e0) (e3)) (op (e2) (op (e2) (e3))))) NIL)
(60B (paramod 19 (1) 60A (1 1)) (not (= (e3) (op (e2) (op (e2) (e3))))) NIL)
(60C (paramod 31 (1) 60B (1 2 2)) (not (= (e3) (op (e2) (e5)))) NIL)
(60D (paramod 33 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(59 (input) (not (= (op (op (e2) (e2)) (e4)) (op (e2) (op (e2) (e4))))) NIL)
(60A (paramod 30 (1) 59 (1 1 1)) (not (= (op (e0) (e4)) (op (e2) (op (e2) (e4))))) NIL)
(60B (paramod 20 (1) 60A (1 1)) (not (= (e4) (op (e2) (op (e2) (e4))))) NIL)
(60C (paramod 32 (1) 60B (1 2 2)) (not (= (e4) (op (e2) (e1)))) NIL)
(60D (paramod 29 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(59 (input) (not (= (op (op (e2) (e2)) (e5)) (op (e2) (op (e2) (e5))))) NIL)
(60A (paramod 30 (1) 59 (1 1 1)) (not (= (op (e0) (e5)) (op (e2) (op (e2) (e5))))) NIL)
(60B (paramod 21 (1) 60A (1 1)) (not (= (e5) (op (e2) (op (e2) (e5))))) NIL)
(60C (paramod 33 (1) 60B (1 2 2)) (not (= (e5) (op (e2) (e3)))) NIL)
(60D (paramod 31 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e2) (e3)) (e0)) (op (e2) (op (e3) (e0))))) NIL)
(60A (paramod 31 (1) 59 (1 1 1)) (not (= (op (e5) (e0)) (op (e2) (op (e3) (e0))))) NIL)
(60B (paramod 46 (1) 60A (1 1)) (not (= (e5) (op (e2) (op (e3) (e0))))) NIL)
(60C (paramod 34 (1) 60B (1 2 2)) (not (= (e5) (op (e2) (e3)))) NIL)
(60D (paramod 31 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e2) (e3)) (e1)) (op (e2) (op (e3) (e1))))) NIL)
(60A (paramod 31 (1) 59 (1 1 1)) (not (= (op (e5) (e1)) (op (e2) (op (e3) (e1))))) NIL)
(60B (paramod 47 (1) 60A (1 1)) (not (= (e3) (op (e2) (op (e3) (e1))))) NIL)
(60C (paramod 35 (1) 60B (1 2 2)) (not (= (e3) (op (e2) (e5)))) NIL)
(60D (paramod 33 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e2) (e3)) (e2)) (op (e2) (op (e3) (e2))))) NIL)
(60A (paramod 31 (1) 59 (1 1 1)) (not (= (op (e5) (e2)) (op (e2) (op (e3) (e2))))) NIL)
(60B (paramod 48 (1) 60A (1 1)) (not (= (e4) (op (e2) (op (e3) (e2))))) NIL)
(60C (paramod 36 (1) 60B (1 2 2)) (not (= (e4) (op (e2) (e1)))) NIL)
(60D (paramod 29 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e2) (e3)) (e3)) (op (e2) (op (e3) (e3))))) NIL)
(60A (paramod 31 (1) 59 (1 1 1)) (not (= (op (e5) (e3)) (op (e2) (op (e3) (e3))))) NIL)
(60B (paramod 49 (1) 60A (1 1)) (not (= (e1) (op (e2) (op (e3) (e3))))) NIL)
(60C (paramod 37 (1) 60B (1 2 2)) (not (= (e1) (op (e2) (e4)))) NIL)
(60D (paramod 32 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e2) (e3)) (e4)) (op (e2) (op (e3) (e4))))) NIL)
(60A (paramod 31 (1) 59 (1 1 1)) (not (= (op (e5) (e4)) (op (e2) (op (e3) (e4))))) NIL)
(60B (paramod 50 (1) 60A (1 1)) (not (= (e2) (op (e2) (op (e3) (e4))))) NIL)
(60C (paramod 38 (1) 60B (1 2 2)) (not (= (e2) (op (e2) (e0)))) NIL)
(60D (paramod 28 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e2) (e3)) (e5)) (op (e2) (op (e3) (e5))))) NIL)
(60A (paramod 31 (1) 59 (1 1 1)) (not (= (op (e5) (e5)) (op (e2) (op (e3) (e5))))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (op (e2) (op (e3) (e5))))) NIL)
(60C (paramod 39 (1) 60B (1 2 2)) (not (= (e0) (op (e2) (e2)))) NIL)
(60D (paramod 30 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(59 (input) (not (= (op (op (e2) (e4)) (e0)) (op (e2) (op (e4) (e0))))) NIL)
(60A (paramod 32 (1) 59 (1 1 1)) (not (= (op (e1) (e0)) (op (e2) (op (e4) (e0))))) NIL)
(60B (paramod 22 (1) 60A (1 1)) (not (= (e1) (op (e2) (op (e4) (e0))))) NIL)
(60C (paramod 40 (1) 60B (1 2 2)) (not (= (e1) (op (e2) (e4)))) NIL)
(60D (paramod 32 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e2) (e4)) (e1)) (op (e2) (op (e4) (e1))))) NIL)
(60A (paramod 32 (1) 59 (1 1 1)) (not (= (op (e1) (e1)) (op (e2) (op (e4) (e1))))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (op (e2) (op (e4) (e1))))) NIL)
(60C (paramod 41 (1) 60B (1 2 2)) (not (= (e0) (op (e2) (e2)))) NIL)
(60D (paramod 30 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(59 (input) (not (= (op (op (e2) (e4)) (e2)) (op (e2) (op (e4) (e2))))) NIL)
(60A (paramod 32 (1) 59 (1 1 1)) (not (= (op (e1) (e2)) (op (e2) (op (e4) (e2))))) NIL)
(60B (paramod 24 (1) 60A (1 1)) (not (= (e3) (op (e2) (op (e4) (e2))))) NIL)
(60C (paramod 42 (1) 60B (1 2 2)) (not (= (e3) (op (e2) (e5)))) NIL)
(60D (paramod 33 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e2) (e4)) (e3)) (op (e2) (op (e4) (e3))))) NIL)
(60A (paramod 32 (1) 59 (1 1 1)) (not (= (op (e1) (e3)) (op (e2) (op (e4) (e3))))) NIL)
(60B (paramod 25 (1) 60A (1 1)) (not (= (e2) (op (e2) (op (e4) (e3))))) NIL)
(60C (paramod 43 (1) 60B (1 2 2)) (not (= (e2) (op (e2) (e0)))) NIL)
(60D (paramod 28 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e2) (e4)) (e4)) (op (e2) (op (e4) (e4))))) NIL)
(60A (paramod 32 (1) 59 (1 1 1)) (not (= (op (e1) (e4)) (op (e2) (op (e4) (e4))))) NIL)
(60B (paramod 26 (1) 60A (1 1)) (not (= (e5) (op (e2) (op (e4) (e4))))) NIL)
(60C (paramod 44 (1) 60B (1 2 2)) (not (= (e5) (op (e2) (e3)))) NIL)
(60D (paramod 31 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e2) (e4)) (e5)) (op (e2) (op (e4) (e5))))) NIL)
(60A (paramod 32 (1) 59 (1 1 1)) (not (= (op (e1) (e5)) (op (e2) (op (e4) (e5))))) NIL)
(60B (paramod 27 (1) 60A (1 1)) (not (= (e4) (op (e2) (op (e4) (e5))))) NIL)
(60C (paramod 45 (1) 60B (1 2 2)) (not (= (e4) (op (e2) (e1)))) NIL)
(60D (paramod 29 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e2) (e5)) (e0)) (op (e2) (op (e5) (e0))))) NIL)
(60A (paramod 33 (1) 59 (1 1 1)) (not (= (op (e3) (e0)) (op (e2) (op (e5) (e0))))) NIL)
(60B (paramod 34 (1) 60A (1 1)) (not (= (e3) (op (e2) (op (e5) (e0))))) NIL)
(60C (paramod 46 (1) 60B (1 2 2)) (not (= (e3) (op (e2) (e5)))) NIL)
(60D (paramod 33 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e2) (e5)) (e1)) (op (e2) (op (e5) (e1))))) NIL)
(60A (paramod 33 (1) 59 (1 1 1)) (not (= (op (e3) (e1)) (op (e2) (op (e5) (e1))))) NIL)
(60B (paramod 35 (1) 60A (1 1)) (not (= (e5) (op (e2) (op (e5) (e1))))) NIL)
(60C (paramod 47 (1) 60B (1 2 2)) (not (= (e5) (op (e2) (e3)))) NIL)
(60D (paramod 31 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e2) (e5)) (e2)) (op (e2) (op (e5) (e2))))) NIL)
(60A (paramod 33 (1) 59 (1 1 1)) (not (= (op (e3) (e2)) (op (e2) (op (e5) (e2))))) NIL)
(60B (paramod 36 (1) 60A (1 1)) (not (= (e1) (op (e2) (op (e5) (e2))))) NIL)
(60C (paramod 48 (1) 60B (1 2 2)) (not (= (e1) (op (e2) (e4)))) NIL)
(60D (paramod 32 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e2) (e5)) (e3)) (op (e2) (op (e5) (e3))))) NIL)
(60A (paramod 33 (1) 59 (1 1 1)) (not (= (op (e3) (e3)) (op (e2) (op (e5) (e3))))) NIL)
(60B (paramod 37 (1) 60A (1 1)) (not (= (e4) (op (e2) (op (e5) (e3))))) NIL)
(60C (paramod 49 (1) 60B (1 2 2)) (not (= (e4) (op (e2) (e1)))) NIL)
(60D (paramod 29 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e2) (e5)) (e4)) (op (e2) (op (e5) (e4))))) NIL)
(60A (paramod 33 (1) 59 (1 1 1)) (not (= (op (e3) (e4)) (op (e2) (op (e5) (e4))))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (op (e2) (op (e5) (e4))))) NIL)
(60C (paramod 50 (1) 60B (1 2 2)) (not (= (e0) (op (e2) (e2)))) NIL)
(60D (paramod 30 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e2) (e5)) (e5)) (op (e2) (op (e5) (e5))))) NIL)
(60A (paramod 33 (1) 59 (1 1 1)) (not (= (op (e3) (e5)) (op (e2) (op (e5) (e5))))) NIL)
(60B (paramod 39 (1) 60A (1 1)) (not (= (e2) (op (e2) (op (e5) (e5))))) NIL)
(60C (paramod 51 (1) 60B (1 2 2)) (not (= (e2) (op (e2) (e0)))) NIL)
(60D (paramod 28 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(59 (input) (not (= (op (op (e3) (e0)) (e0)) (op (e3) (op (e0) (e0))))) NIL)
(60A (paramod 34 (1) 59 (1 1 1)) (not (= (op (e3) (e0)) (op (e3) (op (e0) (e0))))) NIL)
(60B (paramod 34 (1) 60A (1 1)) (not (= (e3) (op (e3) (op (e0) (e0))))) NIL)
(60C (paramod 16 (1) 60B (1 2 2)) (not (= (e3) (op (e3) (e0)))) NIL)
(60D (paramod 34 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(59 (input) (not (= (op (op (e3) (e0)) (e1)) (op (e3) (op (e0) (e1))))) NIL)
(60A (paramod 34 (1) 59 (1 1 1)) (not (= (op (e3) (e1)) (op (e3) (op (e0) (e1))))) NIL)
(60B (paramod 35 (1) 60A (1 1)) (not (= (e5) (op (e3) (op (e0) (e1))))) NIL)
(60C (paramod 17 (1) 60B (1 2 2)) (not (= (e5) (op (e3) (e1)))) NIL)
(60D (paramod 35 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e0)) (e2)) (op (e3) (op (e0) (e2))))) NIL)
(60A (paramod 34 (1) 59 (1 1 1)) (not (= (op (e3) (e2)) (op (e3) (op (e0) (e2))))) NIL)
(60B (paramod 36 (1) 60A (1 1)) (not (= (e1) (op (e3) (op (e0) (e2))))) NIL)
(60C (paramod 18 (1) 60B (1 2 2)) (not (= (e1) (op (e3) (e2)))) NIL)
(60D (paramod 36 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(59 (input) (not (= (op (op (e3) (e0)) (e3)) (op (e3) (op (e0) (e3))))) NIL)
(60A (paramod 34 (1) 59 (1 1 1)) (not (= (op (e3) (e3)) (op (e3) (op (e0) (e3))))) NIL)
(60B (paramod 37 (1) 60A (1 1)) (not (= (e4) (op (e3) (op (e0) (e3))))) NIL)
(60C (paramod 19 (1) 60B (1 2 2)) (not (= (e4) (op (e3) (e3)))) NIL)
(60D (paramod 37 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(59 (input) (not (= (op (op (e3) (e0)) (e4)) (op (e3) (op (e0) (e4))))) NIL)
(60A (paramod 34 (1) 59 (1 1 1)) (not (= (op (e3) (e4)) (op (e3) (op (e0) (e4))))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (op (e3) (op (e0) (e4))))) NIL)
(60C (paramod 20 (1) 60B (1 2 2)) (not (= (e0) (op (e3) (e4)))) NIL)
(60D (paramod 38 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(59 (input) (not (= (op (op (e3) (e0)) (e5)) (op (e3) (op (e0) (e5))))) NIL)
(60A (paramod 34 (1) 59 (1 1 1)) (not (= (op (e3) (e5)) (op (e3) (op (e0) (e5))))) NIL)
(60B (paramod 39 (1) 60A (1 1)) (not (= (e2) (op (e3) (op (e0) (e5))))) NIL)
(60C (paramod 21 (1) 60B (1 2 2)) (not (= (e2) (op (e3) (e5)))) NIL)
(60D (paramod 39 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e3) (e1)) (e0)) (op (e3) (op (e1) (e0))))) NIL)
(60A (paramod 35 (1) 59 (1 1 1)) (not (= (op (e5) (e0)) (op (e3) (op (e1) (e0))))) NIL)
(60B (paramod 46 (1) 60A (1 1)) (not (= (e5) (op (e3) (op (e1) (e0))))) NIL)
(60C (paramod 22 (1) 60B (1 2 2)) (not (= (e5) (op (e3) (e1)))) NIL)
(60D (paramod 35 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e3) (e1)) (e1)) (op (e3) (op (e1) (e1))))) NIL)
(60A (paramod 35 (1) 59 (1 1 1)) (not (= (op (e5) (e1)) (op (e3) (op (e1) (e1))))) NIL)
(60B (paramod 47 (1) 60A (1 1)) (not (= (e3) (op (e3) (op (e1) (e1))))) NIL)
(60C (paramod 23 (1) 60B (1 2 2)) (not (= (e3) (op (e3) (e0)))) NIL)
(60D (paramod 34 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e3) (e1)) (e2)) (op (e3) (op (e1) (e2))))) NIL)
(60A (paramod 35 (1) 59 (1 1 1)) (not (= (op (e5) (e2)) (op (e3) (op (e1) (e2))))) NIL)
(60B (paramod 48 (1) 60A (1 1)) (not (= (e4) (op (e3) (op (e1) (e2))))) NIL)
(60C (paramod 24 (1) 60B (1 2 2)) (not (= (e4) (op (e3) (e3)))) NIL)
(60D (paramod 37 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e1)) (e3)) (op (e3) (op (e1) (e3))))) NIL)
(60A (paramod 35 (1) 59 (1 1 1)) (not (= (op (e5) (e3)) (op (e3) (op (e1) (e3))))) NIL)
(60B (paramod 49 (1) 60A (1 1)) (not (= (e1) (op (e3) (op (e1) (e3))))) NIL)
(60C (paramod 25 (1) 60B (1 2 2)) (not (= (e1) (op (e3) (e2)))) NIL)
(60D (paramod 36 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e3) (e1)) (e4)) (op (e3) (op (e1) (e4))))) NIL)
(60A (paramod 35 (1) 59 (1 1 1)) (not (= (op (e5) (e4)) (op (e3) (op (e1) (e4))))) NIL)
(60B (paramod 50 (1) 60A (1 1)) (not (= (e2) (op (e3) (op (e1) (e4))))) NIL)
(60C (paramod 26 (1) 60B (1 2 2)) (not (= (e2) (op (e3) (e5)))) NIL)
(60D (paramod 39 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e3) (e1)) (e5)) (op (e3) (op (e1) (e5))))) NIL)
(60A (paramod 35 (1) 59 (1 1 1)) (not (= (op (e5) (e5)) (op (e3) (op (e1) (e5))))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (op (e3) (op (e1) (e5))))) NIL)
(60C (paramod 27 (1) 60B (1 2 2)) (not (= (e0) (op (e3) (e4)))) NIL)
(60D (paramod 38 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e2)) (e0)) (op (e3) (op (e2) (e0))))) NIL)
(60A (paramod 36 (1) 59 (1 1 1)) (not (= (op (e1) (e0)) (op (e3) (op (e2) (e0))))) NIL)
(60B (paramod 22 (1) 60A (1 1)) (not (= (e1) (op (e3) (op (e2) (e0))))) NIL)
(60C (paramod 28 (1) 60B (1 2 2)) (not (= (e1) (op (e3) (e2)))) NIL)
(60D (paramod 36 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(59 (input) (not (= (op (op (e3) (e2)) (e1)) (op (e3) (op (e2) (e1))))) NIL)
(60A (paramod 36 (1) 59 (1 1 1)) (not (= (op (e1) (e1)) (op (e3) (op (e2) (e1))))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (op (e3) (op (e2) (e1))))) NIL)
(60C (paramod 29 (1) 60B (1 2 2)) (not (= (e0) (op (e3) (e4)))) NIL)
(60D (paramod 38 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e2)) (e2)) (op (e3) (op (e2) (e2))))) NIL)
(60A (paramod 36 (1) 59 (1 1 1)) (not (= (op (e1) (e2)) (op (e3) (op (e2) (e2))))) NIL)
(60B (paramod 24 (1) 60A (1 1)) (not (= (e3) (op (e3) (op (e2) (e2))))) NIL)
(60C (paramod 30 (1) 60B (1 2 2)) (not (= (e3) (op (e3) (e0)))) NIL)
(60D (paramod 34 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(59 (input) (not (= (op (op (e3) (e2)) (e3)) (op (e3) (op (e2) (e3))))) NIL)
(60A (paramod 36 (1) 59 (1 1 1)) (not (= (op (e1) (e3)) (op (e3) (op (e2) (e3))))) NIL)
(60B (paramod 25 (1) 60A (1 1)) (not (= (e2) (op (e3) (op (e2) (e3))))) NIL)
(60C (paramod 31 (1) 60B (1 2 2)) (not (= (e2) (op (e3) (e5)))) NIL)
(60D (paramod 39 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e2)) (e4)) (op (e3) (op (e2) (e4))))) NIL)
(60A (paramod 36 (1) 59 (1 1 1)) (not (= (op (e1) (e4)) (op (e3) (op (e2) (e4))))) NIL)
(60B (paramod 26 (1) 60A (1 1)) (not (= (e5) (op (e3) (op (e2) (e4))))) NIL)
(60C (paramod 32 (1) 60B (1 2 2)) (not (= (e5) (op (e3) (e1)))) NIL)
(60D (paramod 35 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(59 (input) (not (= (op (op (e3) (e2)) (e5)) (op (e3) (op (e2) (e5))))) NIL)
(60A (paramod 36 (1) 59 (1 1 1)) (not (= (op (e1) (e5)) (op (e3) (op (e2) (e5))))) NIL)
(60B (paramod 27 (1) 60A (1 1)) (not (= (e4) (op (e3) (op (e2) (e5))))) NIL)
(60C (paramod 33 (1) 60B (1 2 2)) (not (= (e4) (op (e3) (e3)))) NIL)
(60D (paramod 37 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(59 (input) (not (= (op (op (e3) (e3)) (e0)) (op (e3) (op (e3) (e0))))) NIL)
(60A (paramod 37 (1) 59 (1 1 1)) (not (= (op (e4) (e0)) (op (e3) (op (e3) (e0))))) NIL)
(60B (paramod 40 (1) 60A (1 1)) (not (= (e4) (op (e3) (op (e3) (e0))))) NIL)
(60C (paramod 34 (1) 60B (1 2 2)) (not (= (e4) (op (e3) (e3)))) NIL)
(60D (paramod 37 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e3) (e3)) (e1)) (op (e3) (op (e3) (e1))))) NIL)
(60A (paramod 37 (1) 59 (1 1 1)) (not (= (op (e4) (e1)) (op (e3) (op (e3) (e1))))) NIL)
(60B (paramod 41 (1) 60A (1 1)) (not (= (e2) (op (e3) (op (e3) (e1))))) NIL)
(60C (paramod 35 (1) 60B (1 2 2)) (not (= (e2) (op (e3) (e5)))) NIL)
(60D (paramod 39 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(59 (input) (not (= (op (op (e3) (e3)) (e2)) (op (e3) (op (e3) (e2))))) NIL)
(60A (paramod 37 (1) 59 (1 1 1)) (not (= (op (e4) (e2)) (op (e3) (op (e3) (e2))))) NIL)
(60B (paramod 42 (1) 60A (1 1)) (not (= (e5) (op (e3) (op (e3) (e2))))) NIL)
(60C (paramod 36 (1) 60B (1 2 2)) (not (= (e5) (op (e3) (e1)))) NIL)
(60D (paramod 35 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e3) (e3)) (e3)) (op (e3) (op (e3) (e3))))) NIL)
(60A (paramod 37 (1) 59 (1 1 1)) (not (= (op (e4) (e3)) (op (e3) (op (e3) (e3))))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (op (e3) (op (e3) (e3))))) NIL)
(60C (paramod 37 (1) 60B (1 2 2)) (not (= (e0) (op (e3) (e4)))) NIL)
(60D (paramod 38 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e3) (e3)) (e4)) (op (e3) (op (e3) (e4))))) NIL)
(60A (paramod 37 (1) 59 (1 1 1)) (not (= (op (e4) (e4)) (op (e3) (op (e3) (e4))))) NIL)
(60B (paramod 44 (1) 60A (1 1)) (not (= (e3) (op (e3) (op (e3) (e4))))) NIL)
(60C (paramod 38 (1) 60B (1 2 2)) (not (= (e3) (op (e3) (e0)))) NIL)
(60D (paramod 34 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e3)) (e5)) (op (e3) (op (e3) (e5))))) NIL)
(60A (paramod 37 (1) 59 (1 1 1)) (not (= (op (e4) (e5)) (op (e3) (op (e3) (e5))))) NIL)
(60B (paramod 45 (1) 60A (1 1)) (not (= (e1) (op (e3) (op (e3) (e5))))) NIL)
(60C (paramod 39 (1) 60B (1 2 2)) (not (= (e1) (op (e3) (e2)))) NIL)
(60D (paramod 36 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(59 (input) (not (= (op (op (e3) (e4)) (e0)) (op (e3) (op (e4) (e0))))) NIL)
(60A (paramod 38 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (op (e3) (op (e4) (e0))))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (op (e3) (op (e4) (e0))))) NIL)
(60C (paramod 40 (1) 60B (1 2 2)) (not (= (e0) (op (e3) (e4)))) NIL)
(60D (paramod 38 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e3) (e4)) (e1)) (op (e3) (op (e4) (e1))))) NIL)
(60A (paramod 38 (1) 59 (1 1 1)) (not (= (op (e0) (e1)) (op (e3) (op (e4) (e1))))) NIL)
(60B (paramod 17 (1) 60A (1 1)) (not (= (e1) (op (e3) (op (e4) (e1))))) NIL)
(60C (paramod 41 (1) 60B (1 2 2)) (not (= (e1) (op (e3) (e2)))) NIL)
(60D (paramod 36 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(59 (input) (not (= (op (op (e3) (e4)) (e2)) (op (e3) (op (e4) (e2))))) NIL)
(60A (paramod 38 (1) 59 (1 1 1)) (not (= (op (e0) (e2)) (op (e3) (op (e4) (e2))))) NIL)
(60B (paramod 18 (1) 60A (1 1)) (not (= (e2) (op (e3) (op (e4) (e2))))) NIL)
(60C (paramod 42 (1) 60B (1 2 2)) (not (= (e2) (op (e3) (e5)))) NIL)
(60D (paramod 39 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e3) (e4)) (e3)) (op (e3) (op (e4) (e3))))) NIL)
(60A (paramod 38 (1) 59 (1 1 1)) (not (= (op (e0) (e3)) (op (e3) (op (e4) (e3))))) NIL)
(60B (paramod 19 (1) 60A (1 1)) (not (= (e3) (op (e3) (op (e4) (e3))))) NIL)
(60C (paramod 43 (1) 60B (1 2 2)) (not (= (e3) (op (e3) (e0)))) NIL)
(60D (paramod 34 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e3) (e4)) (e4)) (op (e3) (op (e4) (e4))))) NIL)
(60A (paramod 38 (1) 59 (1 1 1)) (not (= (op (e0) (e4)) (op (e3) (op (e4) (e4))))) NIL)
(60B (paramod 20 (1) 60A (1 1)) (not (= (e4) (op (e3) (op (e4) (e4))))) NIL)
(60C (paramod 44 (1) 60B (1 2 2)) (not (= (e4) (op (e3) (e3)))) NIL)
(60D (paramod 37 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e4)) (e5)) (op (e3) (op (e4) (e5))))) NIL)
(60A (paramod 38 (1) 59 (1 1 1)) (not (= (op (e0) (e5)) (op (e3) (op (e4) (e5))))) NIL)
(60B (paramod 21 (1) 60A (1 1)) (not (= (e5) (op (e3) (op (e4) (e5))))) NIL)
(60C (paramod 45 (1) 60B (1 2 2)) (not (= (e5) (op (e3) (e1)))) NIL)
(60D (paramod 35 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e3) (e5)) (e0)) (op (e3) (op (e5) (e0))))) NIL)
(60A (paramod 39 (1) 59 (1 1 1)) (not (= (op (e2) (e0)) (op (e3) (op (e5) (e0))))) NIL)
(60B (paramod 28 (1) 60A (1 1)) (not (= (e2) (op (e3) (op (e5) (e0))))) NIL)
(60C (paramod 46 (1) 60B (1 2 2)) (not (= (e2) (op (e3) (e5)))) NIL)
(60D (paramod 39 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e3) (e5)) (e1)) (op (e3) (op (e5) (e1))))) NIL)
(60A (paramod 39 (1) 59 (1 1 1)) (not (= (op (e2) (e1)) (op (e3) (op (e5) (e1))))) NIL)
(60B (paramod 29 (1) 60A (1 1)) (not (= (e4) (op (e3) (op (e5) (e1))))) NIL)
(60C (paramod 47 (1) 60B (1 2 2)) (not (= (e4) (op (e3) (e3)))) NIL)
(60D (paramod 37 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e3) (e5)) (e2)) (op (e3) (op (e5) (e2))))) NIL)
(60A (paramod 39 (1) 59 (1 1 1)) (not (= (op (e2) (e2)) (op (e3) (op (e5) (e2))))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (op (e3) (op (e5) (e2))))) NIL)
(60C (paramod 48 (1) 60B (1 2 2)) (not (= (e0) (op (e3) (e4)))) NIL)
(60D (paramod 38 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e3) (e5)) (e3)) (op (e3) (op (e5) (e3))))) NIL)
(60A (paramod 39 (1) 59 (1 1 1)) (not (= (op (e2) (e3)) (op (e3) (op (e5) (e3))))) NIL)
(60B (paramod 31 (1) 60A (1 1)) (not (= (e5) (op (e3) (op (e5) (e3))))) NIL)
(60C (paramod 49 (1) 60B (1 2 2)) (not (= (e5) (op (e3) (e1)))) NIL)
(60D (paramod 35 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e3) (e5)) (e4)) (op (e3) (op (e5) (e4))))) NIL)
(60A (paramod 39 (1) 59 (1 1 1)) (not (= (op (e2) (e4)) (op (e3) (op (e5) (e4))))) NIL)
(60B (paramod 32 (1) 60A (1 1)) (not (= (e1) (op (e3) (op (e5) (e4))))) NIL)
(60C (paramod 50 (1) 60B (1 2 2)) (not (= (e1) (op (e3) (e2)))) NIL)
(60D (paramod 36 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e3) (e5)) (e5)) (op (e3) (op (e5) (e5))))) NIL)
(60A (paramod 39 (1) 59 (1 1 1)) (not (= (op (e2) (e5)) (op (e3) (op (e5) (e5))))) NIL)
(60B (paramod 33 (1) 60A (1 1)) (not (= (e3) (op (e3) (op (e5) (e5))))) NIL)
(60C (paramod 51 (1) 60B (1 2 2)) (not (= (e3) (op (e3) (e0)))) NIL)
(60D (paramod 34 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(59 (input) (not (= (op (op (e4) (e0)) (e0)) (op (e4) (op (e0) (e0))))) NIL)
(60A (paramod 40 (1) 59 (1 1 1)) (not (= (op (e4) (e0)) (op (e4) (op (e0) (e0))))) NIL)
(60B (paramod 40 (1) 60A (1 1)) (not (= (e4) (op (e4) (op (e0) (e0))))) NIL)
(60C (paramod 16 (1) 60B (1 2 2)) (not (= (e4) (op (e4) (e0)))) NIL)
(60D (paramod 40 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e4) (e0)) (e1)) (op (e4) (op (e0) (e1))))) NIL)
(60A (paramod 40 (1) 59 (1 1 1)) (not (= (op (e4) (e1)) (op (e4) (op (e0) (e1))))) NIL)
(60B (paramod 41 (1) 60A (1 1)) (not (= (e2) (op (e4) (op (e0) (e1))))) NIL)
(60C (paramod 17 (1) 60B (1 2 2)) (not (= (e2) (op (e4) (e1)))) NIL)
(60D (paramod 41 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(59 (input) (not (= (op (op (e4) (e0)) (e2)) (op (e4) (op (e0) (e2))))) NIL)
(60A (paramod 40 (1) 59 (1 1 1)) (not (= (op (e4) (e2)) (op (e4) (op (e0) (e2))))) NIL)
(60B (paramod 42 (1) 60A (1 1)) (not (= (e5) (op (e4) (op (e0) (e2))))) NIL)
(60C (paramod 18 (1) 60B (1 2 2)) (not (= (e5) (op (e4) (e2)))) NIL)
(60D (paramod 42 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e0)) (e3)) (op (e4) (op (e0) (e3))))) NIL)
(60A (paramod 40 (1) 59 (1 1 1)) (not (= (op (e4) (e3)) (op (e4) (op (e0) (e3))))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (op (e4) (op (e0) (e3))))) NIL)
(60C (paramod 19 (1) 60B (1 2 2)) (not (= (e0) (op (e4) (e3)))) NIL)
(60D (paramod 43 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e0)) (e4)) (op (e4) (op (e0) (e4))))) NIL)
(60A (paramod 40 (1) 59 (1 1 1)) (not (= (op (e4) (e4)) (op (e4) (op (e0) (e4))))) NIL)
(60B (paramod 44 (1) 60A (1 1)) (not (= (e3) (op (e4) (op (e0) (e4))))) NIL)
(60C (paramod 20 (1) 60B (1 2 2)) (not (= (e3) (op (e4) (e4)))) NIL)
(60D (paramod 44 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e4) (e0)) (e5)) (op (e4) (op (e0) (e5))))) NIL)
(60A (paramod 40 (1) 59 (1 1 1)) (not (= (op (e4) (e5)) (op (e4) (op (e0) (e5))))) NIL)
(60B (paramod 45 (1) 60A (1 1)) (not (= (e1) (op (e4) (op (e0) (e5))))) NIL)
(60C (paramod 21 (1) 60B (1 2 2)) (not (= (e1) (op (e4) (e5)))) NIL)
(60D (paramod 45 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e4) (e1)) (e0)) (op (e4) (op (e1) (e0))))) NIL)
(60A (paramod 41 (1) 59 (1 1 1)) (not (= (op (e2) (e0)) (op (e4) (op (e1) (e0))))) NIL)
(60B (paramod 28 (1) 60A (1 1)) (not (= (e2) (op (e4) (op (e1) (e0))))) NIL)
(60C (paramod 22 (1) 60B (1 2 2)) (not (= (e2) (op (e4) (e1)))) NIL)
(60D (paramod 41 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(59 (input) (not (= (op (op (e4) (e1)) (e1)) (op (e4) (op (e1) (e1))))) NIL)
(60A (paramod 41 (1) 59 (1 1 1)) (not (= (op (e2) (e1)) (op (e4) (op (e1) (e1))))) NIL)
(60B (paramod 29 (1) 60A (1 1)) (not (= (e4) (op (e4) (op (e1) (e1))))) NIL)
(60C (paramod 23 (1) 60B (1 2 2)) (not (= (e4) (op (e4) (e0)))) NIL)
(60D (paramod 40 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e1)) (e2)) (op (e4) (op (e1) (e2))))) NIL)
(60A (paramod 41 (1) 59 (1 1 1)) (not (= (op (e2) (e2)) (op (e4) (op (e1) (e2))))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (op (e4) (op (e1) (e2))))) NIL)
(60C (paramod 24 (1) 60B (1 2 2)) (not (= (e0) (op (e4) (e3)))) NIL)
(60D (paramod 43 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(59 (input) (not (= (op (op (e4) (e1)) (e3)) (op (e4) (op (e1) (e3))))) NIL)
(60A (paramod 41 (1) 59 (1 1 1)) (not (= (op (e2) (e3)) (op (e4) (op (e1) (e3))))) NIL)
(60B (paramod 31 (1) 60A (1 1)) (not (= (e5) (op (e4) (op (e1) (e3))))) NIL)
(60C (paramod 25 (1) 60B (1 2 2)) (not (= (e5) (op (e4) (e2)))) NIL)
(60D (paramod 42 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e4) (e1)) (e4)) (op (e4) (op (e1) (e4))))) NIL)
(60A (paramod 41 (1) 59 (1 1 1)) (not (= (op (e2) (e4)) (op (e4) (op (e1) (e4))))) NIL)
(60B (paramod 32 (1) 60A (1 1)) (not (= (e1) (op (e4) (op (e1) (e4))))) NIL)
(60C (paramod 26 (1) 60B (1 2 2)) (not (= (e1) (op (e4) (e5)))) NIL)
(60D (paramod 45 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e1)) (e5)) (op (e4) (op (e1) (e5))))) NIL)
(60A (paramod 41 (1) 59 (1 1 1)) (not (= (op (e2) (e5)) (op (e4) (op (e1) (e5))))) NIL)
(60B (paramod 33 (1) 60A (1 1)) (not (= (e3) (op (e4) (op (e1) (e5))))) NIL)
(60C (paramod 27 (1) 60B (1 2 2)) (not (= (e3) (op (e4) (e4)))) NIL)
(60D (paramod 44 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e4) (e2)) (e0)) (op (e4) (op (e2) (e0))))) NIL)
(60A (paramod 42 (1) 59 (1 1 1)) (not (= (op (e5) (e0)) (op (e4) (op (e2) (e0))))) NIL)
(60B (paramod 46 (1) 60A (1 1)) (not (= (e5) (op (e4) (op (e2) (e0))))) NIL)
(60C (paramod 28 (1) 60B (1 2 2)) (not (= (e5) (op (e4) (e2)))) NIL)
(60D (paramod 42 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e2)) (e1)) (op (e4) (op (e2) (e1))))) NIL)
(60A (paramod 42 (1) 59 (1 1 1)) (not (= (op (e5) (e1)) (op (e4) (op (e2) (e1))))) NIL)
(60B (paramod 47 (1) 60A (1 1)) (not (= (e3) (op (e4) (op (e2) (e1))))) NIL)
(60C (paramod 29 (1) 60B (1 2 2)) (not (= (e3) (op (e4) (e4)))) NIL)
(60D (paramod 44 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e4) (e2)) (e2)) (op (e4) (op (e2) (e2))))) NIL)
(60A (paramod 42 (1) 59 (1 1 1)) (not (= (op (e5) (e2)) (op (e4) (op (e2) (e2))))) NIL)
(60B (paramod 48 (1) 60A (1 1)) (not (= (e4) (op (e4) (op (e2) (e2))))) NIL)
(60C (paramod 30 (1) 60B (1 2 2)) (not (= (e4) (op (e4) (e0)))) NIL)
(60D (paramod 40 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e4) (e2)) (e3)) (op (e4) (op (e2) (e3))))) NIL)
(60A (paramod 42 (1) 59 (1 1 1)) (not (= (op (e5) (e3)) (op (e4) (op (e2) (e3))))) NIL)
(60B (paramod 49 (1) 60A (1 1)) (not (= (e1) (op (e4) (op (e2) (e3))))) NIL)
(60C (paramod 31 (1) 60B (1 2 2)) (not (= (e1) (op (e4) (e5)))) NIL)
(60D (paramod 45 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e4) (e2)) (e4)) (op (e4) (op (e2) (e4))))) NIL)
(60A (paramod 42 (1) 59 (1 1 1)) (not (= (op (e5) (e4)) (op (e4) (op (e2) (e4))))) NIL)
(60B (paramod 50 (1) 60A (1 1)) (not (= (e2) (op (e4) (op (e2) (e4))))) NIL)
(60C (paramod 32 (1) 60B (1 2 2)) (not (= (e2) (op (e4) (e1)))) NIL)
(60D (paramod 41 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e2)) (e5)) (op (e4) (op (e2) (e5))))) NIL)
(60A (paramod 42 (1) 59 (1 1 1)) (not (= (op (e5) (e5)) (op (e4) (op (e2) (e5))))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (op (e4) (op (e2) (e5))))) NIL)
(60C (paramod 33 (1) 60B (1 2 2)) (not (= (e0) (op (e4) (e3)))) NIL)
(60D (paramod 43 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e3)) (e0)) (op (e4) (op (e3) (e0))))) NIL)
(60A (paramod 43 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (op (e4) (op (e3) (e0))))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (op (e4) (op (e3) (e0))))) NIL)
(60C (paramod 34 (1) 60B (1 2 2)) (not (= (e0) (op (e4) (e3)))) NIL)
(60D (paramod 43 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e4) (e3)) (e1)) (op (e4) (op (e3) (e1))))) NIL)
(60A (paramod 43 (1) 59 (1 1 1)) (not (= (op (e0) (e1)) (op (e4) (op (e3) (e1))))) NIL)
(60B (paramod 17 (1) 60A (1 1)) (not (= (e1) (op (e4) (op (e3) (e1))))) NIL)
(60C (paramod 35 (1) 60B (1 2 2)) (not (= (e1) (op (e4) (e5)))) NIL)
(60D (paramod 45 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e3)) (e2)) (op (e4) (op (e3) (e2))))) NIL)
(60A (paramod 43 (1) 59 (1 1 1)) (not (= (op (e0) (e2)) (op (e4) (op (e3) (e2))))) NIL)
(60B (paramod 18 (1) 60A (1 1)) (not (= (e2) (op (e4) (op (e3) (e2))))) NIL)
(60C (paramod 36 (1) 60B (1 2 2)) (not (= (e2) (op (e4) (e1)))) NIL)
(60D (paramod 41 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e3)) (e3)) (op (e4) (op (e3) (e3))))) NIL)
(60A (paramod 43 (1) 59 (1 1 1)) (not (= (op (e0) (e3)) (op (e4) (op (e3) (e3))))) NIL)
(60B (paramod 19 (1) 60A (1 1)) (not (= (e3) (op (e4) (op (e3) (e3))))) NIL)
(60C (paramod 37 (1) 60B (1 2 2)) (not (= (e3) (op (e4) (e4)))) NIL)
(60D (paramod 44 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e3)) (e4)) (op (e4) (op (e3) (e4))))) NIL)
(60A (paramod 43 (1) 59 (1 1 1)) (not (= (op (e0) (e4)) (op (e4) (op (e3) (e4))))) NIL)
(60B (paramod 20 (1) 60A (1 1)) (not (= (e4) (op (e4) (op (e3) (e4))))) NIL)
(60C (paramod 38 (1) 60B (1 2 2)) (not (= (e4) (op (e4) (e0)))) NIL)
(60D (paramod 40 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e3)) (e5)) (op (e4) (op (e3) (e5))))) NIL)
(60A (paramod 43 (1) 59 (1 1 1)) (not (= (op (e0) (e5)) (op (e4) (op (e3) (e5))))) NIL)
(60B (paramod 21 (1) 60A (1 1)) (not (= (e5) (op (e4) (op (e3) (e5))))) NIL)
(60C (paramod 39 (1) 60B (1 2 2)) (not (= (e5) (op (e4) (e2)))) NIL)
(60D (paramod 42 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e4)) (e0)) (op (e4) (op (e4) (e0))))) NIL)
(60A (paramod 44 (1) 59 (1 1 1)) (not (= (op (e3) (e0)) (op (e4) (op (e4) (e0))))) NIL)
(60B (paramod 34 (1) 60A (1 1)) (not (= (e3) (op (e4) (op (e4) (e0))))) NIL)
(60C (paramod 40 (1) 60B (1 2 2)) (not (= (e3) (op (e4) (e4)))) NIL)
(60D (paramod 44 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e4)) (e1)) (op (e4) (op (e4) (e1))))) NIL)
(60A (paramod 44 (1) 59 (1 1 1)) (not (= (op (e3) (e1)) (op (e4) (op (e4) (e1))))) NIL)
(60B (paramod 35 (1) 60A (1 1)) (not (= (e5) (op (e4) (op (e4) (e1))))) NIL)
(60C (paramod 41 (1) 60B (1 2 2)) (not (= (e5) (op (e4) (e2)))) NIL)
(60D (paramod 42 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e4) (e4)) (e2)) (op (e4) (op (e4) (e2))))) NIL)
(60A (paramod 44 (1) 59 (1 1 1)) (not (= (op (e3) (e2)) (op (e4) (op (e4) (e2))))) NIL)
(60B (paramod 36 (1) 60A (1 1)) (not (= (e1) (op (e4) (op (e4) (e2))))) NIL)
(60C (paramod 42 (1) 60B (1 2 2)) (not (= (e1) (op (e4) (e5)))) NIL)
(60D (paramod 45 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e4)) (e3)) (op (e4) (op (e4) (e3))))) NIL)
(60A (paramod 44 (1) 59 (1 1 1)) (not (= (op (e3) (e3)) (op (e4) (op (e4) (e3))))) NIL)
(60B (paramod 37 (1) 60A (1 1)) (not (= (e4) (op (e4) (op (e4) (e3))))) NIL)
(60C (paramod 43 (1) 60B (1 2 2)) (not (= (e4) (op (e4) (e0)))) NIL)
(60D (paramod 40 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e4)) (e4)) (op (e4) (op (e4) (e4))))) NIL)
(60A (paramod 44 (1) 59 (1 1 1)) (not (= (op (e3) (e4)) (op (e4) (op (e4) (e4))))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (op (e4) (op (e4) (e4))))) NIL)
(60C (paramod 44 (1) 60B (1 2 2)) (not (= (e0) (op (e4) (e3)))) NIL)
(60D (paramod 43 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(59 (input) (not (= (op (op (e4) (e4)) (e5)) (op (e4) (op (e4) (e5))))) NIL)
(60A (paramod 44 (1) 59 (1 1 1)) (not (= (op (e3) (e5)) (op (e4) (op (e4) (e5))))) NIL)
(60B (paramod 39 (1) 60A (1 1)) (not (= (e2) (op (e4) (op (e4) (e5))))) NIL)
(60C (paramod 45 (1) 60B (1 2 2)) (not (= (e2) (op (e4) (e1)))) NIL)
(60D (paramod 41 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e4) (e5)) (e0)) (op (e4) (op (e5) (e0))))) NIL)
(60A (paramod 45 (1) 59 (1 1 1)) (not (= (op (e1) (e0)) (op (e4) (op (e5) (e0))))) NIL)
(60B (paramod 22 (1) 60A (1 1)) (not (= (e1) (op (e4) (op (e5) (e0))))) NIL)
(60C (paramod 46 (1) 60B (1 2 2)) (not (= (e1) (op (e4) (e5)))) NIL)
(60D (paramod 45 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e4) (e5)) (e1)) (op (e4) (op (e5) (e1))))) NIL)
(60A (paramod 45 (1) 59 (1 1 1)) (not (= (op (e1) (e1)) (op (e4) (op (e5) (e1))))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (op (e4) (op (e5) (e1))))) NIL)
(60C (paramod 47 (1) 60B (1 2 2)) (not (= (e0) (op (e4) (e3)))) NIL)
(60D (paramod 43 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e4) (e5)) (e2)) (op (e4) (op (e5) (e2))))) NIL)
(60A (paramod 45 (1) 59 (1 1 1)) (not (= (op (e1) (e2)) (op (e4) (op (e5) (e2))))) NIL)
(60B (paramod 24 (1) 60A (1 1)) (not (= (e3) (op (e4) (op (e5) (e2))))) NIL)
(60C (paramod 48 (1) 60B (1 2 2)) (not (= (e3) (op (e4) (e4)))) NIL)
(60D (paramod 44 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e4) (e5)) (e3)) (op (e4) (op (e5) (e3))))) NIL)
(60A (paramod 45 (1) 59 (1 1 1)) (not (= (op (e1) (e3)) (op (e4) (op (e5) (e3))))) NIL)
(60B (paramod 25 (1) 60A (1 1)) (not (= (e2) (op (e4) (op (e5) (e3))))) NIL)
(60C (paramod 49 (1) 60B (1 2 2)) (not (= (e2) (op (e4) (e1)))) NIL)
(60D (paramod 41 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e4) (e5)) (e4)) (op (e4) (op (e5) (e4))))) NIL)
(60A (paramod 45 (1) 59 (1 1 1)) (not (= (op (e1) (e4)) (op (e4) (op (e5) (e4))))) NIL)
(60B (paramod 26 (1) 60A (1 1)) (not (= (e5) (op (e4) (op (e5) (e4))))) NIL)
(60C (paramod 50 (1) 60B (1 2 2)) (not (= (e5) (op (e4) (e2)))) NIL)
(60D (paramod 42 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e4) (e5)) (e5)) (op (e4) (op (e5) (e5))))) NIL)
(60A (paramod 45 (1) 59 (1 1 1)) (not (= (op (e1) (e5)) (op (e4) (op (e5) (e5))))) NIL)
(60B (paramod 27 (1) 60A (1 1)) (not (= (e4) (op (e4) (op (e5) (e5))))) NIL)
(60C (paramod 51 (1) 60B (1 2 2)) (not (= (e4) (op (e4) (e0)))) NIL)
(60D (paramod 40 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(59 (input) (not (= (op (op (e5) (e0)) (e0)) (op (e5) (op (e0) (e0))))) NIL)
(60A (paramod 46 (1) 59 (1 1 1)) (not (= (op (e5) (e0)) (op (e5) (op (e0) (e0))))) NIL)
(60B (paramod 46 (1) 60A (1 1)) (not (= (e5) (op (e5) (op (e0) (e0))))) NIL)
(60C (paramod 16 (1) 60B (1 2 2)) (not (= (e5) (op (e5) (e0)))) NIL)
(60D (paramod 46 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e5) (e0)) (e1)) (op (e5) (op (e0) (e1))))) NIL)
(60A (paramod 46 (1) 59 (1 1 1)) (not (= (op (e5) (e1)) (op (e5) (op (e0) (e1))))) NIL)
(60B (paramod 47 (1) 60A (1 1)) (not (= (e3) (op (e5) (op (e0) (e1))))) NIL)
(60C (paramod 17 (1) 60B (1 2 2)) (not (= (e3) (op (e5) (e1)))) NIL)
(60D (paramod 47 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e5) (e0)) (e2)) (op (e5) (op (e0) (e2))))) NIL)
(60A (paramod 46 (1) 59 (1 1 1)) (not (= (op (e5) (e2)) (op (e5) (op (e0) (e2))))) NIL)
(60B (paramod 48 (1) 60A (1 1)) (not (= (e4) (op (e5) (op (e0) (e2))))) NIL)
(60C (paramod 18 (1) 60B (1 2 2)) (not (= (e4) (op (e5) (e2)))) NIL)
(60D (paramod 48 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e5) (e0)) (e3)) (op (e5) (op (e0) (e3))))) NIL)
(60A (paramod 46 (1) 59 (1 1 1)) (not (= (op (e5) (e3)) (op (e5) (op (e0) (e3))))) NIL)
(60B (paramod 49 (1) 60A (1 1)) (not (= (e1) (op (e5) (op (e0) (e3))))) NIL)
(60C (paramod 19 (1) 60B (1 2 2)) (not (= (e1) (op (e5) (e3)))) NIL)
(60D (paramod 49 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e0)) (e4)) (op (e5) (op (e0) (e4))))) NIL)
(60A (paramod 46 (1) 59 (1 1 1)) (not (= (op (e5) (e4)) (op (e5) (op (e0) (e4))))) NIL)
(60B (paramod 50 (1) 60A (1 1)) (not (= (e2) (op (e5) (op (e0) (e4))))) NIL)
(60C (paramod 20 (1) 60B (1 2 2)) (not (= (e2) (op (e5) (e4)))) NIL)
(60D (paramod 50 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e0)) (e5)) (op (e5) (op (e0) (e5))))) NIL)
(60A (paramod 46 (1) 59 (1 1 1)) (not (= (op (e5) (e5)) (op (e5) (op (e0) (e5))))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (op (e5) (op (e0) (e5))))) NIL)
(60C (paramod 21 (1) 60B (1 2 2)) (not (= (e0) (op (e5) (e5)))) NIL)
(60D (paramod 51 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e5) (e1)) (e0)) (op (e5) (op (e1) (e0))))) NIL)
(60A (paramod 47 (1) 59 (1 1 1)) (not (= (op (e3) (e0)) (op (e5) (op (e1) (e0))))) NIL)
(60B (paramod 34 (1) 60A (1 1)) (not (= (e3) (op (e5) (op (e1) (e0))))) NIL)
(60C (paramod 22 (1) 60B (1 2 2)) (not (= (e3) (op (e5) (e1)))) NIL)
(60D (paramod 47 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(59 (input) (not (= (op (op (e5) (e1)) (e1)) (op (e5) (op (e1) (e1))))) NIL)
(60A (paramod 47 (1) 59 (1 1 1)) (not (= (op (e3) (e1)) (op (e5) (op (e1) (e1))))) NIL)
(60B (paramod 35 (1) 60A (1 1)) (not (= (e5) (op (e5) (op (e1) (e1))))) NIL)
(60C (paramod 23 (1) 60B (1 2 2)) (not (= (e5) (op (e5) (e0)))) NIL)
(60D (paramod 46 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e5) (e1)) (e2)) (op (e5) (op (e1) (e2))))) NIL)
(60A (paramod 47 (1) 59 (1 1 1)) (not (= (op (e3) (e2)) (op (e5) (op (e1) (e2))))) NIL)
(60B (paramod 36 (1) 60A (1 1)) (not (= (e1) (op (e5) (op (e1) (e2))))) NIL)
(60C (paramod 24 (1) 60B (1 2 2)) (not (= (e1) (op (e5) (e3)))) NIL)
(60D (paramod 49 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e5) (e1)) (e3)) (op (e5) (op (e1) (e3))))) NIL)
(60A (paramod 47 (1) 59 (1 1 1)) (not (= (op (e3) (e3)) (op (e5) (op (e1) (e3))))) NIL)
(60B (paramod 37 (1) 60A (1 1)) (not (= (e4) (op (e5) (op (e1) (e3))))) NIL)
(60C (paramod 25 (1) 60B (1 2 2)) (not (= (e4) (op (e5) (e2)))) NIL)
(60D (paramod 48 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e1)) (e4)) (op (e5) (op (e1) (e4))))) NIL)
(60A (paramod 47 (1) 59 (1 1 1)) (not (= (op (e3) (e4)) (op (e5) (op (e1) (e4))))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (op (e5) (op (e1) (e4))))) NIL)
(60C (paramod 26 (1) 60B (1 2 2)) (not (= (e0) (op (e5) (e5)))) NIL)
(60D (paramod 51 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e1)) (e5)) (op (e5) (op (e1) (e5))))) NIL)
(60A (paramod 47 (1) 59 (1 1 1)) (not (= (op (e3) (e5)) (op (e5) (op (e1) (e5))))) NIL)
(60B (paramod 39 (1) 60A (1 1)) (not (= (e2) (op (e5) (op (e1) (e5))))) NIL)
(60C (paramod 27 (1) 60B (1 2 2)) (not (= (e2) (op (e5) (e4)))) NIL)
(60D (paramod 50 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e5) (e2)) (e0)) (op (e5) (op (e2) (e0))))) NIL)
(60A (paramod 48 (1) 59 (1 1 1)) (not (= (op (e4) (e0)) (op (e5) (op (e2) (e0))))) NIL)
(60B (paramod 40 (1) 60A (1 1)) (not (= (e4) (op (e5) (op (e2) (e0))))) NIL)
(60C (paramod 28 (1) 60B (1 2 2)) (not (= (e4) (op (e5) (e2)))) NIL)
(60D (paramod 48 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e2)) (e1)) (op (e5) (op (e2) (e1))))) NIL)
(60A (paramod 48 (1) 59 (1 1 1)) (not (= (op (e4) (e1)) (op (e5) (op (e2) (e1))))) NIL)
(60B (paramod 41 (1) 60A (1 1)) (not (= (e2) (op (e5) (op (e2) (e1))))) NIL)
(60C (paramod 29 (1) 60B (1 2 2)) (not (= (e2) (op (e5) (e4)))) NIL)
(60D (paramod 50 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e5) (e2)) (e2)) (op (e5) (op (e2) (e2))))) NIL)
(60A (paramod 48 (1) 59 (1 1 1)) (not (= (op (e4) (e2)) (op (e5) (op (e2) (e2))))) NIL)
(60B (paramod 42 (1) 60A (1 1)) (not (= (e5) (op (e5) (op (e2) (e2))))) NIL)
(60C (paramod 30 (1) 60B (1 2 2)) (not (= (e5) (op (e5) (e0)))) NIL)
(60D (paramod 46 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e2)) (e3)) (op (e5) (op (e2) (e3))))) NIL)
(60A (paramod 48 (1) 59 (1 1 1)) (not (= (op (e4) (e3)) (op (e5) (op (e2) (e3))))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (op (e5) (op (e2) (e3))))) NIL)
(60C (paramod 31 (1) 60B (1 2 2)) (not (= (e0) (op (e5) (e5)))) NIL)
(60D (paramod 51 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(59 (input) (not (= (op (op (e5) (e2)) (e4)) (op (e5) (op (e2) (e4))))) NIL)
(60A (paramod 48 (1) 59 (1 1 1)) (not (= (op (e4) (e4)) (op (e5) (op (e2) (e4))))) NIL)
(60B (paramod 44 (1) 60A (1 1)) (not (= (e3) (op (e5) (op (e2) (e4))))) NIL)
(60C (paramod 32 (1) 60B (1 2 2)) (not (= (e3) (op (e5) (e1)))) NIL)
(60D (paramod 47 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e5) (e2)) (e5)) (op (e5) (op (e2) (e5))))) NIL)
(60A (paramod 48 (1) 59 (1 1 1)) (not (= (op (e4) (e5)) (op (e5) (op (e2) (e5))))) NIL)
(60B (paramod 45 (1) 60A (1 1)) (not (= (e1) (op (e5) (op (e2) (e5))))) NIL)
(60C (paramod 33 (1) 60B (1 2 2)) (not (= (e1) (op (e5) (e3)))) NIL)
(60D (paramod 49 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e5) (e3)) (e0)) (op (e5) (op (e3) (e0))))) NIL)
(60A (paramod 49 (1) 59 (1 1 1)) (not (= (op (e1) (e0)) (op (e5) (op (e3) (e0))))) NIL)
(60B (paramod 22 (1) 60A (1 1)) (not (= (e1) (op (e5) (op (e3) (e0))))) NIL)
(60C (paramod 34 (1) 60B (1 2 2)) (not (= (e1) (op (e5) (e3)))) NIL)
(60D (paramod 49 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(35 (input) (= (op (e3) (e1)) (e5)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e3)) (e1)) (op (e5) (op (e3) (e1))))) NIL)
(60A (paramod 49 (1) 59 (1 1 1)) (not (= (op (e1) (e1)) (op (e5) (op (e3) (e1))))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (op (e5) (op (e3) (e1))))) NIL)
(60C (paramod 35 (1) 60B (1 2 2)) (not (= (e0) (op (e5) (e5)))) NIL)
(60D (paramod 51 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(24 (input) (= (op (e1) (e2)) (e3)) NIL)
(36 (input) (= (op (e3) (e2)) (e1)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e5) (e3)) (e2)) (op (e5) (op (e3) (e2))))) NIL)
(60A (paramod 49 (1) 59 (1 1 1)) (not (= (op (e1) (e2)) (op (e5) (op (e3) (e2))))) NIL)
(60B (paramod 24 (1) 60A (1 1)) (not (= (e3) (op (e5) (op (e3) (e2))))) NIL)
(60C (paramod 36 (1) 60B (1 2 2)) (not (= (e3) (op (e5) (e1)))) NIL)
(60D (paramod 47 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(25 (input) (= (op (e1) (e3)) (e2)) NIL)
(37 (input) (= (op (e3) (e3)) (e4)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e3)) (e3)) (op (e5) (op (e3) (e3))))) NIL)
(60A (paramod 49 (1) 59 (1 1 1)) (not (= (op (e1) (e3)) (op (e5) (op (e3) (e3))))) NIL)
(60B (paramod 25 (1) 60A (1 1)) (not (= (e2) (op (e5) (op (e3) (e3))))) NIL)
(60C (paramod 37 (1) 60B (1 2 2)) (not (= (e2) (op (e5) (e4)))) NIL)
(60D (paramod 50 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(26 (input) (= (op (e1) (e4)) (e5)) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e5) (e3)) (e4)) (op (e5) (op (e3) (e4))))) NIL)
(60A (paramod 49 (1) 59 (1 1 1)) (not (= (op (e1) (e4)) (op (e5) (op (e3) (e4))))) NIL)
(60B (paramod 26 (1) 60A (1 1)) (not (= (e5) (op (e5) (op (e3) (e4))))) NIL)
(60C (paramod 38 (1) 60B (1 2 2)) (not (= (e5) (op (e5) (e0)))) NIL)
(60D (paramod 46 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(27 (input) (= (op (e1) (e5)) (e4)) NIL)
(39 (input) (= (op (e3) (e5)) (e2)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(59 (input) (not (= (op (op (e5) (e3)) (e5)) (op (e5) (op (e3) (e5))))) NIL)
(60A (paramod 49 (1) 59 (1 1 1)) (not (= (op (e1) (e5)) (op (e5) (op (e3) (e5))))) NIL)
(60B (paramod 27 (1) 60A (1 1)) (not (= (e4) (op (e5) (op (e3) (e5))))) NIL)
(60C (paramod 39 (1) 60B (1 2 2)) (not (= (e4) (op (e5) (e2)))) NIL)
(60D (paramod 48 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e4)) (e0)) (op (e5) (op (e4) (e0))))) NIL)
(60A (paramod 50 (1) 59 (1 1 1)) (not (= (op (e2) (e0)) (op (e5) (op (e4) (e0))))) NIL)
(60B (paramod 28 (1) 60A (1 1)) (not (= (e2) (op (e5) (op (e4) (e0))))) NIL)
(60C (paramod 40 (1) 60B (1 2 2)) (not (= (e2) (op (e5) (e4)))) NIL)
(60D (paramod 50 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(29 (input) (= (op (e2) (e1)) (e4)) NIL)
(41 (input) (= (op (e4) (e1)) (e2)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e4)) (e1)) (op (e5) (op (e4) (e1))))) NIL)
(60A (paramod 50 (1) 59 (1 1 1)) (not (= (op (e2) (e1)) (op (e5) (op (e4) (e1))))) NIL)
(60B (paramod 29 (1) 60A (1 1)) (not (= (e4) (op (e5) (op (e4) (e1))))) NIL)
(60C (paramod 41 (1) 60B (1 2 2)) (not (= (e4) (op (e5) (e2)))) NIL)
(60D (paramod 48 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(42 (input) (= (op (e4) (e2)) (e5)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e4)) (e2)) (op (e5) (op (e4) (e2))))) NIL)
(60A (paramod 50 (1) 59 (1 1 1)) (not (= (op (e2) (e2)) (op (e5) (op (e4) (e2))))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (op (e5) (op (e4) (e2))))) NIL)
(60C (paramod 42 (1) 60B (1 2 2)) (not (= (e0) (op (e5) (e5)))) NIL)
(60D (paramod 51 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(31 (input) (= (op (e2) (e3)) (e5)) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e4)) (e3)) (op (e5) (op (e4) (e3))))) NIL)
(60A (paramod 50 (1) 59 (1 1 1)) (not (= (op (e2) (e3)) (op (e5) (op (e4) (e3))))) NIL)
(60B (paramod 31 (1) 60A (1 1)) (not (= (e5) (op (e5) (op (e4) (e3))))) NIL)
(60C (paramod 43 (1) 60B (1 2 2)) (not (= (e5) (op (e5) (e0)))) NIL)
(60D (paramod 46 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(32 (input) (= (op (e2) (e4)) (e1)) NIL)
(44 (input) (= (op (e4) (e4)) (e3)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e4)) (e4)) (op (e5) (op (e4) (e4))))) NIL)
(60A (paramod 50 (1) 59 (1 1 1)) (not (= (op (e2) (e4)) (op (e5) (op (e4) (e4))))) NIL)
(60B (paramod 32 (1) 60A (1 1)) (not (= (e1) (op (e5) (op (e4) (e4))))) NIL)
(60C (paramod 44 (1) 60B (1 2 2)) (not (= (e1) (op (e5) (e3)))) NIL)
(60D (paramod 49 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(33 (input) (= (op (e2) (e5)) (e3)) NIL)
(45 (input) (= (op (e4) (e5)) (e1)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(59 (input) (not (= (op (op (e5) (e4)) (e5)) (op (e5) (op (e4) (e5))))) NIL)
(60A (paramod 50 (1) 59 (1 1 1)) (not (= (op (e2) (e5)) (op (e5) (op (e4) (e5))))) NIL)
(60B (paramod 33 (1) 60A (1 1)) (not (= (e3) (op (e5) (op (e4) (e5))))) NIL)
(60C (paramod 45 (1) 60B (1 2 2)) (not (= (e3) (op (e5) (e1)))) NIL)
(60D (paramod 47 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e5)) (e0)) (op (e5) (op (e5) (e0))))) NIL)
(60A (paramod 51 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (op (e5) (op (e5) (e0))))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (op (e5) (op (e5) (e0))))) NIL)
(60C (paramod 46 (1) 60B (1 2 2)) (not (= (e0) (op (e5) (e5)))) NIL)
(60D (paramod 51 (1) 60C (1 2)) (not (= (e0) (e0))) NIL)
(65 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e5)) (e1)) (op (e5) (op (e5) (e1))))) NIL)
(60A (paramod 51 (1) 59 (1 1 1)) (not (= (op (e0) (e1)) (op (e5) (op (e5) (e1))))) NIL)
(60B (paramod 17 (1) 60A (1 1)) (not (= (e1) (op (e5) (op (e5) (e1))))) NIL)
(60C (paramod 47 (1) 60B (1 2 2)) (not (= (e1) (op (e5) (e3)))) NIL)
(60D (paramod 49 (1) 60C (1 2)) (not (= (e1) (e1))) NIL)
(65 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e5)) (e2)) (op (e5) (op (e5) (e2))))) NIL)
(60A (paramod 51 (1) 59 (1 1 1)) (not (= (op (e0) (e2)) (op (e5) (op (e5) (e2))))) NIL)
(60B (paramod 18 (1) 60A (1 1)) (not (= (e2) (op (e5) (op (e5) (e2))))) NIL)
(60C (paramod 48 (1) 60B (1 2 2)) (not (= (e2) (op (e5) (e4)))) NIL)
(60D (paramod 50 (1) 60C (1 2)) (not (= (e2) (e2))) NIL)
(65 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(47 (input) (= (op (e5) (e1)) (e3)) NIL)
(49 (input) (= (op (e5) (e3)) (e1)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e5)) (e3)) (op (e5) (op (e5) (e3))))) NIL)
(60A (paramod 51 (1) 59 (1 1 1)) (not (= (op (e0) (e3)) (op (e5) (op (e5) (e3))))) NIL)
(60B (paramod 19 (1) 60A (1 1)) (not (= (e3) (op (e5) (op (e5) (e3))))) NIL)
(60C (paramod 49 (1) 60B (1 2 2)) (not (= (e3) (op (e5) (e1)))) NIL)
(60D (paramod 47 (1) 60C (1 2)) (not (= (e3) (e3))) NIL)
(65 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(48 (input) (= (op (e5) (e2)) (e4)) NIL)
(50 (input) (= (op (e5) (e4)) (e2)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e5)) (e4)) (op (e5) (op (e5) (e4))))) NIL)
(60A (paramod 51 (1) 59 (1 1 1)) (not (= (op (e0) (e4)) (op (e5) (op (e5) (e4))))) NIL)
(60B (paramod 20 (1) 60A (1 1)) (not (= (e4) (op (e5) (op (e5) (e4))))) NIL)
(60C (paramod 50 (1) 60B (1 2 2)) (not (= (e4) (op (e5) (e2)))) NIL)
(60D (paramod 48 (1) 60C (1 2)) (not (= (e4) (e4))) NIL)
(65 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(59 (input) (not (= (op (op (e5) (e5)) (e5)) (op (e5) (op (e5) (e5))))) NIL)
(60A (paramod 51 (1) 59 (1 1 1)) (not (= (op (e0) (e5)) (op (e5) (op (e5) (e5))))) NIL)
(60B (paramod 21 (1) 60A (1 1)) (not (= (e5) (op (e5) (op (e5) (e5))))) NIL)
(60C (paramod 51 (1) 60B (1 2 2)) (not (= (e5) (op (e5) (e0)))) NIL)
(60D (paramod 46 (1) 60C (1 2)) (not (= (e5) (e5))) NIL)
(65 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60D () 65 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (unit) (e0)) (e0))) NIL)
(60A (paramod 52 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (e0))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (e0))) NIL)
(63 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (e0) (unit)) (e0))) NIL)
(60A (paramod 52 (1) 59 (1 1 2)) (not (= (op (e0) (e0)) (e0))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (e0))) NIL)
(63 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(17 (input) (= (op (e0) (e1)) (e1)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (unit) (e1)) (e1))) NIL)
(60A (paramod 52 (1) 59 (1 1 1)) (not (= (op (e0) (e1)) (e1))) NIL)
(60B (paramod 17 (1) 60A (1 1)) (not (= (e1) (e1))) NIL)
(63 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(22 (input) (= (op (e1) (e0)) (e1)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (e1) (unit)) (e1))) NIL)
(60A (paramod 52 (1) 59 (1 1 2)) (not (= (op (e1) (e0)) (e1))) NIL)
(60B (paramod 22 (1) 60A (1 1)) (not (= (e1) (e1))) NIL)
(63 (instantiate 0 ((v0 . (e1)))) (= (e1) (e1)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(18 (input) (= (op (e0) (e2)) (e2)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (unit) (e2)) (e2))) NIL)
(60A (paramod 52 (1) 59 (1 1 1)) (not (= (op (e0) (e2)) (e2))) NIL)
(60B (paramod 18 (1) 60A (1 1)) (not (= (e2) (e2))) NIL)
(63 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(28 (input) (= (op (e2) (e0)) (e2)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (e2) (unit)) (e2))) NIL)
(60A (paramod 52 (1) 59 (1 1 2)) (not (= (op (e2) (e0)) (e2))) NIL)
(60B (paramod 28 (1) 60A (1 1)) (not (= (e2) (e2))) NIL)
(63 (instantiate 0 ((v0 . (e2)))) (= (e2) (e2)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(19 (input) (= (op (e0) (e3)) (e3)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (unit) (e3)) (e3))) NIL)
(60A (paramod 52 (1) 59 (1 1 1)) (not (= (op (e0) (e3)) (e3))) NIL)
(60B (paramod 19 (1) 60A (1 1)) (not (= (e3) (e3))) NIL)
(63 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(34 (input) (= (op (e3) (e0)) (e3)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (e3) (unit)) (e3))) NIL)
(60A (paramod 52 (1) 59 (1 1 2)) (not (= (op (e3) (e0)) (e3))) NIL)
(60B (paramod 34 (1) 60A (1 1)) (not (= (e3) (e3))) NIL)
(63 (instantiate 0 ((v0 . (e3)))) (= (e3) (e3)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(20 (input) (= (op (e0) (e4)) (e4)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (unit) (e4)) (e4))) NIL)
(60A (paramod 52 (1) 59 (1 1 1)) (not (= (op (e0) (e4)) (e4))) NIL)
(60B (paramod 20 (1) 60A (1 1)) (not (= (e4) (e4))) NIL)
(63 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(40 (input) (= (op (e4) (e0)) (e4)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (e4) (unit)) (e4))) NIL)
(60A (paramod 52 (1) 59 (1 1 2)) (not (= (op (e4) (e0)) (e4))) NIL)
(60B (paramod 40 (1) 60A (1 1)) (not (= (e4) (e4))) NIL)
(63 (instantiate 0 ((v0 . (e4)))) (= (e4) (e4)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(21 (input) (= (op (e0) (e5)) (e5)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (unit) (e5)) (e5))) NIL)
(60A (paramod 52 (1) 59 (1 1 1)) (not (= (op (e0) (e5)) (e5))) NIL)
(60B (paramod 21 (1) 60A (1 1)) (not (= (e5) (e5))) NIL)
(63 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(46 (input) (= (op (e5) (e0)) (e5)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(59 (input) (not (= (op (e5) (unit)) (e5))) NIL)
(60A (paramod 52 (1) 59 (1 1 2)) (not (= (op (e5) (e0)) (e5))) NIL)
(60B (paramod 46 (1) 60A (1 1)) (not (= (e5) (e5))) NIL)
(63 (instantiate 0 ((v0 . (e5)))) (= (e5) (e5)) NIL)
(60 (resolve 60B () 63 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(53 (input) (= (inv (e0)) (e0)) NIL)
(59 (input) (not (= (op (e0) (inv (e0))) (unit))) NIL)
(60A (paramod 53 (1) 59 (1 1 2)) (not (= (op (e0) (e0)) (unit))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(16 (input) (= (op (e0) (e0)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(53 (input) (= (inv (e0)) (e0)) NIL)
(59 (input) (not (= (op (inv (e0)) (e0)) (unit))) NIL)
(60A (paramod 53 (1) 59 (1 1 1)) (not (= (op (e0) (e0)) (unit))) NIL)
(60B (paramod 16 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(54 (input) (= (inv (e1)) (e1)) NIL)
(59 (input) (not (= (op (e1) (inv (e1))) (unit))) NIL)
(60A (paramod 54 (1) 59 (1 1 2)) (not (= (op (e1) (e1)) (unit))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(23 (input) (= (op (e1) (e1)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(54 (input) (= (inv (e1)) (e1)) NIL)
(59 (input) (not (= (op (inv (e1)) (e1)) (unit))) NIL)
(60A (paramod 54 (1) 59 (1 1 1)) (not (= (op (e1) (e1)) (unit))) NIL)
(60B (paramod 23 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(55 (input) (= (inv (e2)) (e2)) NIL)
(59 (input) (not (= (op (e2) (inv (e2))) (unit))) NIL)
(60A (paramod 55 (1) 59 (1 1 2)) (not (= (op (e2) (e2)) (unit))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(30 (input) (= (op (e2) (e2)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(55 (input) (= (inv (e2)) (e2)) NIL)
(59 (input) (not (= (op (inv (e2)) (e2)) (unit))) NIL)
(60A (paramod 55 (1) 59 (1 1 1)) (not (= (op (e2) (e2)) (unit))) NIL)
(60B (paramod 30 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(56 (input) (= (inv (e3)) (e4)) NIL)
(59 (input) (not (= (op (e3) (inv (e3))) (unit))) NIL)
(60A (paramod 56 (1) 59 (1 1 2)) (not (= (op (e3) (e4)) (unit))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(56 (input) (= (inv (e3)) (e4)) NIL)
(59 (input) (not (= (op (inv (e3)) (e3)) (unit))) NIL)
(60A (paramod 56 (1) 59 (1 1 1)) (not (= (op (e4) (e3)) (unit))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(43 (input) (= (op (e4) (e3)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(57 (input) (= (inv (e4)) (e3)) NIL)
(59 (input) (not (= (op (e4) (inv (e4))) (unit))) NIL)
(60A (paramod 57 (1) 59 (1 1 2)) (not (= (op (e4) (e3)) (unit))) NIL)
(60B (paramod 43 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(38 (input) (= (op (e3) (e4)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(57 (input) (= (inv (e4)) (e3)) NIL)
(59 (input) (not (= (op (inv (e4)) (e4)) (unit))) NIL)
(60A (paramod 57 (1) 59 (1 1 1)) (not (= (op (e3) (e4)) (unit))) NIL)
(60B (paramod 38 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(58 (input) (= (inv (e5)) (e5)) NIL)
(59 (input) (not (= (op (e5) (inv (e5))) (unit))) NIL)
(60A (paramod 58 (1) 59 (1 1 2)) (not (= (op (e5) (e5)) (unit))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT

;; BEGINNING OF PROOF OBJECT
(
(0 (input) (= v0 v0) NIL)
(51 (input) (= (op (e5) (e5)) (e0)) NIL)
(52 (input) (= (unit) (e0)) NIL)
(58 (input) (= (inv (e5)) (e5)) NIL)
(59 (input) (not (= (op (inv (e5)) (e5)) (unit))) NIL)
(60A (paramod 58 (1) 59 (1 1 1)) (not (= (op (e5) (e5)) (unit))) NIL)
(60B (paramod 51 (1) 60A (1 1)) (not (= (e0) (unit))) NIL)
(60C (paramod 52 (1) 60B (1 2)) (not (= (e0) (e0))) NIL)
(64 (instantiate 0 ((v0 . (e0)))) (= (e0) (e0)) NIL)
(60 (resolve 60C () 64 ()) false NIL)
)
;; END OF PROOF OBJECT
