#!/bin/csh

if ($#argv != 3) then
	echo "need 3 args: extension-1 extension-2 (problem-set-file | directory)"
	exit(1)
endif

set x1=$1
set x2=$2

if -d $3 then
    set group=$3
else
    set group=`cat $3`
endif

foreach d ($group)
    echo "================= Starting problem set $d ================="
    cd $d

    foreach f1 (*.$x1)
        set f2 = $f1:r.$x2
        set g1=`egrep "Generated|Selections" $f1 | tail -1`
        set g2=`egrep "Generated|Selections" $f2 | tail -1`
        if ( "$g1" != "$g2" ) then
            echo "different, $f1  : $g1"
            echo "           $f2 : $g2"
        endif
    end

    cd ..
end
