#!/bin/csh

if ($#argv != 2) then
	echo "need 2 args: bin-directory ouput-extension"
	exit(1)
endif

set d=$1
set out=$2

limit cputime 180

# job na-ring-1

$d/prover9 -f na-ring-1.in > na-ring-1.$out

# job na-ring-2

$d/mace4 -c -N20 -f na-ring-2.in > na-ring-2.$out

# job na-ring-3

$d/prover9 -f na-ring-3.in > na-ring-3.$out

# job x3-ring

$d/prover9 -f x3-ring.in > x3-ring.$out

# job rp-ident

$d/prover9 -f rp-ident.in >  rp-ident.$out

# job rp-ring

$d/mace4 -f rp-ring.in > rp-ring.$out

# job cand3

$d/mace4 -f cand3.in > cand3.$out

# job cand10

$d/mace4 -f cand10.in > cand10.$out

# job cand23

$d/mace4 -f cand23.in > cand23.$out

# job gtsax

$d/prover9 -f gtsax.in > gtsax.$out
