#!/bin/csh

if ($#argv != 2) then
	echo "need 2 args: extension-1 extension-2"
	exit(1)
endif

set x1=$1
set x2=$2

foreach f1 (*.$x1)
    set f2 = $f1:r.$x2
    set g1=`egrep "Generated|Selections" $f1 | tail -1`
    set g2=`egrep "Generated|Selections" $f2 | tail -1`
    if ( "$g1" != "$g2" ) then
	echo "different, $f1  : $g1"
	echo "           $f2 : $g2"
    endif
end
