#!/bin/csh


if ($#argv != 2) then
	echo "need 2 args: bin-directory ouput-extension"
	exit(1)
endif

set d=$1
set out=$2

# job ab

$d/prover9 -f head.in ab.in > ab.$out

# job bc

$d/prover9 -f head.in bc.in > bc.$out

# job bcs

$d/prover9 -f head.in bcs.in > bcs.$out

# job cd

$d/prover9 -f head.in cd.in > cd.$out

# job csd

$d/prover9 -f head.in csd.in > csd.$out

# job t2_12

$d/prover9 -f head.in t2_12.in > t2_12.$out

# job t2_23

$d/prover9 -f head.in t2_23.in > t2_23.$out

# job t3_12

$d/prover9 -f head.in t3_12.in > t3_12.$out

# job t4_12

$d/prover9 -f head.in t4_12.in > t4_12.$out

