#!/bin/csh

if ($#argv != 2) then
	echo "need 2 args: bin-directory (problem-set-file | directory)"
	exit(1)
endif

set bin=$1

if -d $2 then
    set group=$2
else
    set group=`cat $2`
endif


foreach d ($group)
    echo "================= Starting problem set $d ================="
    cd $d
    foreach i (*.out)
	head -1 $i | egrep "= (Prover9|FOF-Prover9) =" > /dev/null
	if ($status == 0) then
	    $bin/directproof -f $i > $i:r.direct
	    grep 'forward_proof, all' $i:r.direct > /dev/null
	    if ($status == 0) /bin/rm $i:r.direct
	    continue
	else
	    echo "    Skipping $i, because it's not Prover9 output."
	endif

    end
    cd ..
end
