#!/bin/csh

if ($#argv != 3) then
	echo "need 3 args: extension-1 extension-2 (problem-set-file | directory)"
	exit(1)
endif

set x1=$1
set x2=$2

if -d $3 then
    set group=$3
else
    set group=`cat $3`
endif

foreach d ($group)
    echo "================= Starting problem set $d ================="
    cd $d

    echo "renamimg: "
    ls *.$x1

    foreach i (*.$x1)
        /bin/mv $i $i:r.$x2
    end

    cd ..

end
