#!/bin/csh

limit cputime 3600

if ($#argv != 3) then
	echo "need 3 args: binary-directory ouput-extension (problem-set-file | directory)"
	exit(1)
endif

set bin=$1
set out=$2

if -d $3 then
    set group=$3
else
    set group=`cat $3`
endif

foreach d ($group)
    echo "================= Starting problem set $d ================="
    cd $d
    ./go $bin $out
    cd ..
end
