#!/bin/csh

if ($#argv != 1) then
	echo "need 1 arg: bin-directory"
	exit(1)
endif

set bin=$1

foreach i ( *.out )

    head -1 $i | egrep "= (Prover9|FOF-Prover9) =" > /dev/null
    if ($status == 0) then
	echo "prooftrans xml -f $i"
	$bin/prooftrans xml -f $i > $i.xml
	continue
    endif

    head -1 $i | grep "= Mace4 =" > /dev/null
    if ($status == 0) then
	echo "interpformat xml -f $i"
	$bin/interpformat xml -f $i > $i.xml
	continue
    endif

    grep "^interpretation(" $i > /dev/null
    if ($status == 0) then
	echo "interpformat xml -f $i"
	$bin/interpformat xml -f $i > $i.xml
	continue
    endif

end
	
