#!/bin/csh


if ($#argv != 2) then
	echo "need 2 args: bin-directory ouput-extension"
	exit(1)
endif

set d=$1
set out=$2

# job BA3

$d/prover9 -f BA3.in > BA3.$out

# job mol-hints

# $d/prover9 -f mol-hints.in > mol-hints.$out

# job oml6

$d/prover9 -f oml6.in > oml6.$out

# job RBA-2

$d/prover9 -f RBA-2.in > RBA-2.$out

# job bw

$d/prover9 -f bw.in > bw.$out

# job w_sk

$d/prover9 -f w_sk.in > w_sk.$out

# job xcb-reflex

$d/prover9 -f xcb-reflex.in > xcb-reflex.$out

# job steam

$d/prover9 -f steam.in > steam.$out

# job subset_trans

$d/prover9 -f subset_trans.in > subset_trans.$out

# job HWV006-1

$d/prover9 -f HWV006-1.in > HWV006-1.$out

# job lifsch

$d/prover9 -f lifsch.in > lifsch.$out
